// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\SimulinkCFARHDLWorkflowExampleNew\Compensatory_Lag_Cells_HDL.v
// Created: 2023-05-30 17:04:46
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Compensatory_Lag_Cells_HDL
// Source Path: SimulinkCFARHDLWorkflowExampleNew/CFAR Implementation Model/CFAR Core/Training HDL/Compensatory Lag 
// Cells HD
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Compensatory_Lag_Cells_HDL
          (clk,
           reset,
           enb,
           CUTidx,
           Lag_Delay,
           Compensatory_Lag_Sum);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] CUTidx;  // int16
  input   signed [33:0] Lag_Delay;  // sfix34_En12
  output  signed [33:0] Compensatory_Lag_Sum;  // sfix34_En12


  wire signed [15:0] Ncell_out1;  // int16
  reg signed [15:0] Delay9_reg [0:1];  // sfix16 [2]
  wire signed [15:0] Delay9_reg_next [0:1];  // sfix16 [2]
  wire signed [15:0] Delay9_out1;  // int16
  wire signed [15:0] alpha_out1;  // int16
  reg signed [15:0] Delay2_out1;  // int16
  wire signed [15:0] alpha_out1_1;  // int16
  reg signed [15:0] Delay4_out1;  // int16
  wire signed [15:0] CUT_NT_NG_op_stage1;  // sfix16
  reg signed [15:0] Delay5_reg [0:202];  // sfix16 [203]
  wire signed [15:0] Delay5_reg_next [0:202];  // sfix16 [203]
  wire signed [15:0] Delay5_out1;  // int16
  wire signed [15:0] CUT_NT_NG_out1;  // int16
  reg signed [15:0] Delay10_out1;  // int16
  wire signed [15:0] Add_out1;  // int16
  reg signed [15:0] Delay12_out1;  // int16
  wire switch_compare_1;
  reg signed [33:0] PreviousLag1_reg [0:102];  // sfix34 [103]
  wire signed [33:0] PreviousLag1_reg_next [0:102];  // sfix34_En12 [103]
  wire signed [33:0] PreviousLag1_out1;  // sfix34_En12
  wire signed [33:0] alpha_out1_2;  // sfix34_En12
  wire signed [33:0] Compare_to_0_out1;  // sfix34_En12
  reg signed [33:0] Delay14_out1;  // sfix34_En12
  reg signed [33:0] PreviousLag2_reg [0:99];  // sfix34 [100]
  wire signed [33:0] PreviousLag2_reg_next [0:99];  // sfix34_En12 [100]
  wire signed [33:0] PreviousLag2_out1;  // sfix34_En12
  wire signed [33:0] Add8_out1;  // sfix34_En12
  reg signed [33:0] Delay3_out1;  // sfix34_En12
  reg signed [33:0] Delay7_out1;  // sfix34_En12
  wire signed [34:0] Add9_add_cast;  // sfix35_En12
  wire signed [34:0] Add9_add_cast_1;  // sfix35_En12
  wire signed [34:0] Add9_add_temp;  // sfix35_En12
  wire signed [33:0] Add9_out1;  // sfix34_En12


  assign Ncell_out1 = 16'sb0000100100101001;



  always @(posedge clk or posedge reset)
    begin : Delay9_process
      if (reset == 1'b1) begin
        Delay9_reg[0] <= 16'sb0000000000000000;
        Delay9_reg[1] <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay9_reg[0] <= Delay9_reg_next[0];
          Delay9_reg[1] <= Delay9_reg_next[1];
        end
      end
    end

  assign Delay9_out1 = Delay9_reg[1];
  assign Delay9_reg_next[0] = Ncell_out1;
  assign Delay9_reg_next[1] = Delay9_reg[0];



  assign alpha_out1 = 16'sb0000000001100100;



  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= alpha_out1;
        end
      end
    end



  assign alpha_out1_1 = 16'sb0000000000000010;



  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay4_out1 <= alpha_out1_1;
        end
      end
    end



  assign CUT_NT_NG_op_stage1 = Delay2_out1 + Delay4_out1;



  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_reg[0] <= 16'sb0000000000000000;
        Delay5_reg[1] <= 16'sb0000000000000000;
        Delay5_reg[2] <= 16'sb0000000000000000;
        Delay5_reg[3] <= 16'sb0000000000000000;
        Delay5_reg[4] <= 16'sb0000000000000000;
        Delay5_reg[5] <= 16'sb0000000000000000;
        Delay5_reg[6] <= 16'sb0000000000000000;
        Delay5_reg[7] <= 16'sb0000000000000000;
        Delay5_reg[8] <= 16'sb0000000000000000;
        Delay5_reg[9] <= 16'sb0000000000000000;
        Delay5_reg[10] <= 16'sb0000000000000000;
        Delay5_reg[11] <= 16'sb0000000000000000;
        Delay5_reg[12] <= 16'sb0000000000000000;
        Delay5_reg[13] <= 16'sb0000000000000000;
        Delay5_reg[14] <= 16'sb0000000000000000;
        Delay5_reg[15] <= 16'sb0000000000000000;
        Delay5_reg[16] <= 16'sb0000000000000000;
        Delay5_reg[17] <= 16'sb0000000000000000;
        Delay5_reg[18] <= 16'sb0000000000000000;
        Delay5_reg[19] <= 16'sb0000000000000000;
        Delay5_reg[20] <= 16'sb0000000000000000;
        Delay5_reg[21] <= 16'sb0000000000000000;
        Delay5_reg[22] <= 16'sb0000000000000000;
        Delay5_reg[23] <= 16'sb0000000000000000;
        Delay5_reg[24] <= 16'sb0000000000000000;
        Delay5_reg[25] <= 16'sb0000000000000000;
        Delay5_reg[26] <= 16'sb0000000000000000;
        Delay5_reg[27] <= 16'sb0000000000000000;
        Delay5_reg[28] <= 16'sb0000000000000000;
        Delay5_reg[29] <= 16'sb0000000000000000;
        Delay5_reg[30] <= 16'sb0000000000000000;
        Delay5_reg[31] <= 16'sb0000000000000000;
        Delay5_reg[32] <= 16'sb0000000000000000;
        Delay5_reg[33] <= 16'sb0000000000000000;
        Delay5_reg[34] <= 16'sb0000000000000000;
        Delay5_reg[35] <= 16'sb0000000000000000;
        Delay5_reg[36] <= 16'sb0000000000000000;
        Delay5_reg[37] <= 16'sb0000000000000000;
        Delay5_reg[38] <= 16'sb0000000000000000;
        Delay5_reg[39] <= 16'sb0000000000000000;
        Delay5_reg[40] <= 16'sb0000000000000000;
        Delay5_reg[41] <= 16'sb0000000000000000;
        Delay5_reg[42] <= 16'sb0000000000000000;
        Delay5_reg[43] <= 16'sb0000000000000000;
        Delay5_reg[44] <= 16'sb0000000000000000;
        Delay5_reg[45] <= 16'sb0000000000000000;
        Delay5_reg[46] <= 16'sb0000000000000000;
        Delay5_reg[47] <= 16'sb0000000000000000;
        Delay5_reg[48] <= 16'sb0000000000000000;
        Delay5_reg[49] <= 16'sb0000000000000000;
        Delay5_reg[50] <= 16'sb0000000000000000;
        Delay5_reg[51] <= 16'sb0000000000000000;
        Delay5_reg[52] <= 16'sb0000000000000000;
        Delay5_reg[53] <= 16'sb0000000000000000;
        Delay5_reg[54] <= 16'sb0000000000000000;
        Delay5_reg[55] <= 16'sb0000000000000000;
        Delay5_reg[56] <= 16'sb0000000000000000;
        Delay5_reg[57] <= 16'sb0000000000000000;
        Delay5_reg[58] <= 16'sb0000000000000000;
        Delay5_reg[59] <= 16'sb0000000000000000;
        Delay5_reg[60] <= 16'sb0000000000000000;
        Delay5_reg[61] <= 16'sb0000000000000000;
        Delay5_reg[62] <= 16'sb0000000000000000;
        Delay5_reg[63] <= 16'sb0000000000000000;
        Delay5_reg[64] <= 16'sb0000000000000000;
        Delay5_reg[65] <= 16'sb0000000000000000;
        Delay5_reg[66] <= 16'sb0000000000000000;
        Delay5_reg[67] <= 16'sb0000000000000000;
        Delay5_reg[68] <= 16'sb0000000000000000;
        Delay5_reg[69] <= 16'sb0000000000000000;
        Delay5_reg[70] <= 16'sb0000000000000000;
        Delay5_reg[71] <= 16'sb0000000000000000;
        Delay5_reg[72] <= 16'sb0000000000000000;
        Delay5_reg[73] <= 16'sb0000000000000000;
        Delay5_reg[74] <= 16'sb0000000000000000;
        Delay5_reg[75] <= 16'sb0000000000000000;
        Delay5_reg[76] <= 16'sb0000000000000000;
        Delay5_reg[77] <= 16'sb0000000000000000;
        Delay5_reg[78] <= 16'sb0000000000000000;
        Delay5_reg[79] <= 16'sb0000000000000000;
        Delay5_reg[80] <= 16'sb0000000000000000;
        Delay5_reg[81] <= 16'sb0000000000000000;
        Delay5_reg[82] <= 16'sb0000000000000000;
        Delay5_reg[83] <= 16'sb0000000000000000;
        Delay5_reg[84] <= 16'sb0000000000000000;
        Delay5_reg[85] <= 16'sb0000000000000000;
        Delay5_reg[86] <= 16'sb0000000000000000;
        Delay5_reg[87] <= 16'sb0000000000000000;
        Delay5_reg[88] <= 16'sb0000000000000000;
        Delay5_reg[89] <= 16'sb0000000000000000;
        Delay5_reg[90] <= 16'sb0000000000000000;
        Delay5_reg[91] <= 16'sb0000000000000000;
        Delay5_reg[92] <= 16'sb0000000000000000;
        Delay5_reg[93] <= 16'sb0000000000000000;
        Delay5_reg[94] <= 16'sb0000000000000000;
        Delay5_reg[95] <= 16'sb0000000000000000;
        Delay5_reg[96] <= 16'sb0000000000000000;
        Delay5_reg[97] <= 16'sb0000000000000000;
        Delay5_reg[98] <= 16'sb0000000000000000;
        Delay5_reg[99] <= 16'sb0000000000000000;
        Delay5_reg[100] <= 16'sb0000000000000000;
        Delay5_reg[101] <= 16'sb0000000000000000;
        Delay5_reg[102] <= 16'sb0000000000000000;
        Delay5_reg[103] <= 16'sb0000000000000000;
        Delay5_reg[104] <= 16'sb0000000000000000;
        Delay5_reg[105] <= 16'sb0000000000000000;
        Delay5_reg[106] <= 16'sb0000000000000000;
        Delay5_reg[107] <= 16'sb0000000000000000;
        Delay5_reg[108] <= 16'sb0000000000000000;
        Delay5_reg[109] <= 16'sb0000000000000000;
        Delay5_reg[110] <= 16'sb0000000000000000;
        Delay5_reg[111] <= 16'sb0000000000000000;
        Delay5_reg[112] <= 16'sb0000000000000000;
        Delay5_reg[113] <= 16'sb0000000000000000;
        Delay5_reg[114] <= 16'sb0000000000000000;
        Delay5_reg[115] <= 16'sb0000000000000000;
        Delay5_reg[116] <= 16'sb0000000000000000;
        Delay5_reg[117] <= 16'sb0000000000000000;
        Delay5_reg[118] <= 16'sb0000000000000000;
        Delay5_reg[119] <= 16'sb0000000000000000;
        Delay5_reg[120] <= 16'sb0000000000000000;
        Delay5_reg[121] <= 16'sb0000000000000000;
        Delay5_reg[122] <= 16'sb0000000000000000;
        Delay5_reg[123] <= 16'sb0000000000000000;
        Delay5_reg[124] <= 16'sb0000000000000000;
        Delay5_reg[125] <= 16'sb0000000000000000;
        Delay5_reg[126] <= 16'sb0000000000000000;
        Delay5_reg[127] <= 16'sb0000000000000000;
        Delay5_reg[128] <= 16'sb0000000000000000;
        Delay5_reg[129] <= 16'sb0000000000000000;
        Delay5_reg[130] <= 16'sb0000000000000000;
        Delay5_reg[131] <= 16'sb0000000000000000;
        Delay5_reg[132] <= 16'sb0000000000000000;
        Delay5_reg[133] <= 16'sb0000000000000000;
        Delay5_reg[134] <= 16'sb0000000000000000;
        Delay5_reg[135] <= 16'sb0000000000000000;
        Delay5_reg[136] <= 16'sb0000000000000000;
        Delay5_reg[137] <= 16'sb0000000000000000;
        Delay5_reg[138] <= 16'sb0000000000000000;
        Delay5_reg[139] <= 16'sb0000000000000000;
        Delay5_reg[140] <= 16'sb0000000000000000;
        Delay5_reg[141] <= 16'sb0000000000000000;
        Delay5_reg[142] <= 16'sb0000000000000000;
        Delay5_reg[143] <= 16'sb0000000000000000;
        Delay5_reg[144] <= 16'sb0000000000000000;
        Delay5_reg[145] <= 16'sb0000000000000000;
        Delay5_reg[146] <= 16'sb0000000000000000;
        Delay5_reg[147] <= 16'sb0000000000000000;
        Delay5_reg[148] <= 16'sb0000000000000000;
        Delay5_reg[149] <= 16'sb0000000000000000;
        Delay5_reg[150] <= 16'sb0000000000000000;
        Delay5_reg[151] <= 16'sb0000000000000000;
        Delay5_reg[152] <= 16'sb0000000000000000;
        Delay5_reg[153] <= 16'sb0000000000000000;
        Delay5_reg[154] <= 16'sb0000000000000000;
        Delay5_reg[155] <= 16'sb0000000000000000;
        Delay5_reg[156] <= 16'sb0000000000000000;
        Delay5_reg[157] <= 16'sb0000000000000000;
        Delay5_reg[158] <= 16'sb0000000000000000;
        Delay5_reg[159] <= 16'sb0000000000000000;
        Delay5_reg[160] <= 16'sb0000000000000000;
        Delay5_reg[161] <= 16'sb0000000000000000;
        Delay5_reg[162] <= 16'sb0000000000000000;
        Delay5_reg[163] <= 16'sb0000000000000000;
        Delay5_reg[164] <= 16'sb0000000000000000;
        Delay5_reg[165] <= 16'sb0000000000000000;
        Delay5_reg[166] <= 16'sb0000000000000000;
        Delay5_reg[167] <= 16'sb0000000000000000;
        Delay5_reg[168] <= 16'sb0000000000000000;
        Delay5_reg[169] <= 16'sb0000000000000000;
        Delay5_reg[170] <= 16'sb0000000000000000;
        Delay5_reg[171] <= 16'sb0000000000000000;
        Delay5_reg[172] <= 16'sb0000000000000000;
        Delay5_reg[173] <= 16'sb0000000000000000;
        Delay5_reg[174] <= 16'sb0000000000000000;
        Delay5_reg[175] <= 16'sb0000000000000000;
        Delay5_reg[176] <= 16'sb0000000000000000;
        Delay5_reg[177] <= 16'sb0000000000000000;
        Delay5_reg[178] <= 16'sb0000000000000000;
        Delay5_reg[179] <= 16'sb0000000000000000;
        Delay5_reg[180] <= 16'sb0000000000000000;
        Delay5_reg[181] <= 16'sb0000000000000000;
        Delay5_reg[182] <= 16'sb0000000000000000;
        Delay5_reg[183] <= 16'sb0000000000000000;
        Delay5_reg[184] <= 16'sb0000000000000000;
        Delay5_reg[185] <= 16'sb0000000000000000;
        Delay5_reg[186] <= 16'sb0000000000000000;
        Delay5_reg[187] <= 16'sb0000000000000000;
        Delay5_reg[188] <= 16'sb0000000000000000;
        Delay5_reg[189] <= 16'sb0000000000000000;
        Delay5_reg[190] <= 16'sb0000000000000000;
        Delay5_reg[191] <= 16'sb0000000000000000;
        Delay5_reg[192] <= 16'sb0000000000000000;
        Delay5_reg[193] <= 16'sb0000000000000000;
        Delay5_reg[194] <= 16'sb0000000000000000;
        Delay5_reg[195] <= 16'sb0000000000000000;
        Delay5_reg[196] <= 16'sb0000000000000000;
        Delay5_reg[197] <= 16'sb0000000000000000;
        Delay5_reg[198] <= 16'sb0000000000000000;
        Delay5_reg[199] <= 16'sb0000000000000000;
        Delay5_reg[200] <= 16'sb0000000000000000;
        Delay5_reg[201] <= 16'sb0000000000000000;
        Delay5_reg[202] <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay5_reg[0] <= Delay5_reg_next[0];
          Delay5_reg[1] <= Delay5_reg_next[1];
          Delay5_reg[2] <= Delay5_reg_next[2];
          Delay5_reg[3] <= Delay5_reg_next[3];
          Delay5_reg[4] <= Delay5_reg_next[4];
          Delay5_reg[5] <= Delay5_reg_next[5];
          Delay5_reg[6] <= Delay5_reg_next[6];
          Delay5_reg[7] <= Delay5_reg_next[7];
          Delay5_reg[8] <= Delay5_reg_next[8];
          Delay5_reg[9] <= Delay5_reg_next[9];
          Delay5_reg[10] <= Delay5_reg_next[10];
          Delay5_reg[11] <= Delay5_reg_next[11];
          Delay5_reg[12] <= Delay5_reg_next[12];
          Delay5_reg[13] <= Delay5_reg_next[13];
          Delay5_reg[14] <= Delay5_reg_next[14];
          Delay5_reg[15] <= Delay5_reg_next[15];
          Delay5_reg[16] <= Delay5_reg_next[16];
          Delay5_reg[17] <= Delay5_reg_next[17];
          Delay5_reg[18] <= Delay5_reg_next[18];
          Delay5_reg[19] <= Delay5_reg_next[19];
          Delay5_reg[20] <= Delay5_reg_next[20];
          Delay5_reg[21] <= Delay5_reg_next[21];
          Delay5_reg[22] <= Delay5_reg_next[22];
          Delay5_reg[23] <= Delay5_reg_next[23];
          Delay5_reg[24] <= Delay5_reg_next[24];
          Delay5_reg[25] <= Delay5_reg_next[25];
          Delay5_reg[26] <= Delay5_reg_next[26];
          Delay5_reg[27] <= Delay5_reg_next[27];
          Delay5_reg[28] <= Delay5_reg_next[28];
          Delay5_reg[29] <= Delay5_reg_next[29];
          Delay5_reg[30] <= Delay5_reg_next[30];
          Delay5_reg[31] <= Delay5_reg_next[31];
          Delay5_reg[32] <= Delay5_reg_next[32];
          Delay5_reg[33] <= Delay5_reg_next[33];
          Delay5_reg[34] <= Delay5_reg_next[34];
          Delay5_reg[35] <= Delay5_reg_next[35];
          Delay5_reg[36] <= Delay5_reg_next[36];
          Delay5_reg[37] <= Delay5_reg_next[37];
          Delay5_reg[38] <= Delay5_reg_next[38];
          Delay5_reg[39] <= Delay5_reg_next[39];
          Delay5_reg[40] <= Delay5_reg_next[40];
          Delay5_reg[41] <= Delay5_reg_next[41];
          Delay5_reg[42] <= Delay5_reg_next[42];
          Delay5_reg[43] <= Delay5_reg_next[43];
          Delay5_reg[44] <= Delay5_reg_next[44];
          Delay5_reg[45] <= Delay5_reg_next[45];
          Delay5_reg[46] <= Delay5_reg_next[46];
          Delay5_reg[47] <= Delay5_reg_next[47];
          Delay5_reg[48] <= Delay5_reg_next[48];
          Delay5_reg[49] <= Delay5_reg_next[49];
          Delay5_reg[50] <= Delay5_reg_next[50];
          Delay5_reg[51] <= Delay5_reg_next[51];
          Delay5_reg[52] <= Delay5_reg_next[52];
          Delay5_reg[53] <= Delay5_reg_next[53];
          Delay5_reg[54] <= Delay5_reg_next[54];
          Delay5_reg[55] <= Delay5_reg_next[55];
          Delay5_reg[56] <= Delay5_reg_next[56];
          Delay5_reg[57] <= Delay5_reg_next[57];
          Delay5_reg[58] <= Delay5_reg_next[58];
          Delay5_reg[59] <= Delay5_reg_next[59];
          Delay5_reg[60] <= Delay5_reg_next[60];
          Delay5_reg[61] <= Delay5_reg_next[61];
          Delay5_reg[62] <= Delay5_reg_next[62];
          Delay5_reg[63] <= Delay5_reg_next[63];
          Delay5_reg[64] <= Delay5_reg_next[64];
          Delay5_reg[65] <= Delay5_reg_next[65];
          Delay5_reg[66] <= Delay5_reg_next[66];
          Delay5_reg[67] <= Delay5_reg_next[67];
          Delay5_reg[68] <= Delay5_reg_next[68];
          Delay5_reg[69] <= Delay5_reg_next[69];
          Delay5_reg[70] <= Delay5_reg_next[70];
          Delay5_reg[71] <= Delay5_reg_next[71];
          Delay5_reg[72] <= Delay5_reg_next[72];
          Delay5_reg[73] <= Delay5_reg_next[73];
          Delay5_reg[74] <= Delay5_reg_next[74];
          Delay5_reg[75] <= Delay5_reg_next[75];
          Delay5_reg[76] <= Delay5_reg_next[76];
          Delay5_reg[77] <= Delay5_reg_next[77];
          Delay5_reg[78] <= Delay5_reg_next[78];
          Delay5_reg[79] <= Delay5_reg_next[79];
          Delay5_reg[80] <= Delay5_reg_next[80];
          Delay5_reg[81] <= Delay5_reg_next[81];
          Delay5_reg[82] <= Delay5_reg_next[82];
          Delay5_reg[83] <= Delay5_reg_next[83];
          Delay5_reg[84] <= Delay5_reg_next[84];
          Delay5_reg[85] <= Delay5_reg_next[85];
          Delay5_reg[86] <= Delay5_reg_next[86];
          Delay5_reg[87] <= Delay5_reg_next[87];
          Delay5_reg[88] <= Delay5_reg_next[88];
          Delay5_reg[89] <= Delay5_reg_next[89];
          Delay5_reg[90] <= Delay5_reg_next[90];
          Delay5_reg[91] <= Delay5_reg_next[91];
          Delay5_reg[92] <= Delay5_reg_next[92];
          Delay5_reg[93] <= Delay5_reg_next[93];
          Delay5_reg[94] <= Delay5_reg_next[94];
          Delay5_reg[95] <= Delay5_reg_next[95];
          Delay5_reg[96] <= Delay5_reg_next[96];
          Delay5_reg[97] <= Delay5_reg_next[97];
          Delay5_reg[98] <= Delay5_reg_next[98];
          Delay5_reg[99] <= Delay5_reg_next[99];
          Delay5_reg[100] <= Delay5_reg_next[100];
          Delay5_reg[101] <= Delay5_reg_next[101];
          Delay5_reg[102] <= Delay5_reg_next[102];
          Delay5_reg[103] <= Delay5_reg_next[103];
          Delay5_reg[104] <= Delay5_reg_next[104];
          Delay5_reg[105] <= Delay5_reg_next[105];
          Delay5_reg[106] <= Delay5_reg_next[106];
          Delay5_reg[107] <= Delay5_reg_next[107];
          Delay5_reg[108] <= Delay5_reg_next[108];
          Delay5_reg[109] <= Delay5_reg_next[109];
          Delay5_reg[110] <= Delay5_reg_next[110];
          Delay5_reg[111] <= Delay5_reg_next[111];
          Delay5_reg[112] <= Delay5_reg_next[112];
          Delay5_reg[113] <= Delay5_reg_next[113];
          Delay5_reg[114] <= Delay5_reg_next[114];
          Delay5_reg[115] <= Delay5_reg_next[115];
          Delay5_reg[116] <= Delay5_reg_next[116];
          Delay5_reg[117] <= Delay5_reg_next[117];
          Delay5_reg[118] <= Delay5_reg_next[118];
          Delay5_reg[119] <= Delay5_reg_next[119];
          Delay5_reg[120] <= Delay5_reg_next[120];
          Delay5_reg[121] <= Delay5_reg_next[121];
          Delay5_reg[122] <= Delay5_reg_next[122];
          Delay5_reg[123] <= Delay5_reg_next[123];
          Delay5_reg[124] <= Delay5_reg_next[124];
          Delay5_reg[125] <= Delay5_reg_next[125];
          Delay5_reg[126] <= Delay5_reg_next[126];
          Delay5_reg[127] <= Delay5_reg_next[127];
          Delay5_reg[128] <= Delay5_reg_next[128];
          Delay5_reg[129] <= Delay5_reg_next[129];
          Delay5_reg[130] <= Delay5_reg_next[130];
          Delay5_reg[131] <= Delay5_reg_next[131];
          Delay5_reg[132] <= Delay5_reg_next[132];
          Delay5_reg[133] <= Delay5_reg_next[133];
          Delay5_reg[134] <= Delay5_reg_next[134];
          Delay5_reg[135] <= Delay5_reg_next[135];
          Delay5_reg[136] <= Delay5_reg_next[136];
          Delay5_reg[137] <= Delay5_reg_next[137];
          Delay5_reg[138] <= Delay5_reg_next[138];
          Delay5_reg[139] <= Delay5_reg_next[139];
          Delay5_reg[140] <= Delay5_reg_next[140];
          Delay5_reg[141] <= Delay5_reg_next[141];
          Delay5_reg[142] <= Delay5_reg_next[142];
          Delay5_reg[143] <= Delay5_reg_next[143];
          Delay5_reg[144] <= Delay5_reg_next[144];
          Delay5_reg[145] <= Delay5_reg_next[145];
          Delay5_reg[146] <= Delay5_reg_next[146];
          Delay5_reg[147] <= Delay5_reg_next[147];
          Delay5_reg[148] <= Delay5_reg_next[148];
          Delay5_reg[149] <= Delay5_reg_next[149];
          Delay5_reg[150] <= Delay5_reg_next[150];
          Delay5_reg[151] <= Delay5_reg_next[151];
          Delay5_reg[152] <= Delay5_reg_next[152];
          Delay5_reg[153] <= Delay5_reg_next[153];
          Delay5_reg[154] <= Delay5_reg_next[154];
          Delay5_reg[155] <= Delay5_reg_next[155];
          Delay5_reg[156] <= Delay5_reg_next[156];
          Delay5_reg[157] <= Delay5_reg_next[157];
          Delay5_reg[158] <= Delay5_reg_next[158];
          Delay5_reg[159] <= Delay5_reg_next[159];
          Delay5_reg[160] <= Delay5_reg_next[160];
          Delay5_reg[161] <= Delay5_reg_next[161];
          Delay5_reg[162] <= Delay5_reg_next[162];
          Delay5_reg[163] <= Delay5_reg_next[163];
          Delay5_reg[164] <= Delay5_reg_next[164];
          Delay5_reg[165] <= Delay5_reg_next[165];
          Delay5_reg[166] <= Delay5_reg_next[166];
          Delay5_reg[167] <= Delay5_reg_next[167];
          Delay5_reg[168] <= Delay5_reg_next[168];
          Delay5_reg[169] <= Delay5_reg_next[169];
          Delay5_reg[170] <= Delay5_reg_next[170];
          Delay5_reg[171] <= Delay5_reg_next[171];
          Delay5_reg[172] <= Delay5_reg_next[172];
          Delay5_reg[173] <= Delay5_reg_next[173];
          Delay5_reg[174] <= Delay5_reg_next[174];
          Delay5_reg[175] <= Delay5_reg_next[175];
          Delay5_reg[176] <= Delay5_reg_next[176];
          Delay5_reg[177] <= Delay5_reg_next[177];
          Delay5_reg[178] <= Delay5_reg_next[178];
          Delay5_reg[179] <= Delay5_reg_next[179];
          Delay5_reg[180] <= Delay5_reg_next[180];
          Delay5_reg[181] <= Delay5_reg_next[181];
          Delay5_reg[182] <= Delay5_reg_next[182];
          Delay5_reg[183] <= Delay5_reg_next[183];
          Delay5_reg[184] <= Delay5_reg_next[184];
          Delay5_reg[185] <= Delay5_reg_next[185];
          Delay5_reg[186] <= Delay5_reg_next[186];
          Delay5_reg[187] <= Delay5_reg_next[187];
          Delay5_reg[188] <= Delay5_reg_next[188];
          Delay5_reg[189] <= Delay5_reg_next[189];
          Delay5_reg[190] <= Delay5_reg_next[190];
          Delay5_reg[191] <= Delay5_reg_next[191];
          Delay5_reg[192] <= Delay5_reg_next[192];
          Delay5_reg[193] <= Delay5_reg_next[193];
          Delay5_reg[194] <= Delay5_reg_next[194];
          Delay5_reg[195] <= Delay5_reg_next[195];
          Delay5_reg[196] <= Delay5_reg_next[196];
          Delay5_reg[197] <= Delay5_reg_next[197];
          Delay5_reg[198] <= Delay5_reg_next[198];
          Delay5_reg[199] <= Delay5_reg_next[199];
          Delay5_reg[200] <= Delay5_reg_next[200];
          Delay5_reg[201] <= Delay5_reg_next[201];
          Delay5_reg[202] <= Delay5_reg_next[202];
        end
      end
    end

  assign Delay5_out1 = Delay5_reg[202];
  assign Delay5_reg_next[0] = CUTidx;
  assign Delay5_reg_next[1] = Delay5_reg[0];
  assign Delay5_reg_next[2] = Delay5_reg[1];
  assign Delay5_reg_next[3] = Delay5_reg[2];
  assign Delay5_reg_next[4] = Delay5_reg[3];
  assign Delay5_reg_next[5] = Delay5_reg[4];
  assign Delay5_reg_next[6] = Delay5_reg[5];
  assign Delay5_reg_next[7] = Delay5_reg[6];
  assign Delay5_reg_next[8] = Delay5_reg[7];
  assign Delay5_reg_next[9] = Delay5_reg[8];
  assign Delay5_reg_next[10] = Delay5_reg[9];
  assign Delay5_reg_next[11] = Delay5_reg[10];
  assign Delay5_reg_next[12] = Delay5_reg[11];
  assign Delay5_reg_next[13] = Delay5_reg[12];
  assign Delay5_reg_next[14] = Delay5_reg[13];
  assign Delay5_reg_next[15] = Delay5_reg[14];
  assign Delay5_reg_next[16] = Delay5_reg[15];
  assign Delay5_reg_next[17] = Delay5_reg[16];
  assign Delay5_reg_next[18] = Delay5_reg[17];
  assign Delay5_reg_next[19] = Delay5_reg[18];
  assign Delay5_reg_next[20] = Delay5_reg[19];
  assign Delay5_reg_next[21] = Delay5_reg[20];
  assign Delay5_reg_next[22] = Delay5_reg[21];
  assign Delay5_reg_next[23] = Delay5_reg[22];
  assign Delay5_reg_next[24] = Delay5_reg[23];
  assign Delay5_reg_next[25] = Delay5_reg[24];
  assign Delay5_reg_next[26] = Delay5_reg[25];
  assign Delay5_reg_next[27] = Delay5_reg[26];
  assign Delay5_reg_next[28] = Delay5_reg[27];
  assign Delay5_reg_next[29] = Delay5_reg[28];
  assign Delay5_reg_next[30] = Delay5_reg[29];
  assign Delay5_reg_next[31] = Delay5_reg[30];
  assign Delay5_reg_next[32] = Delay5_reg[31];
  assign Delay5_reg_next[33] = Delay5_reg[32];
  assign Delay5_reg_next[34] = Delay5_reg[33];
  assign Delay5_reg_next[35] = Delay5_reg[34];
  assign Delay5_reg_next[36] = Delay5_reg[35];
  assign Delay5_reg_next[37] = Delay5_reg[36];
  assign Delay5_reg_next[38] = Delay5_reg[37];
  assign Delay5_reg_next[39] = Delay5_reg[38];
  assign Delay5_reg_next[40] = Delay5_reg[39];
  assign Delay5_reg_next[41] = Delay5_reg[40];
  assign Delay5_reg_next[42] = Delay5_reg[41];
  assign Delay5_reg_next[43] = Delay5_reg[42];
  assign Delay5_reg_next[44] = Delay5_reg[43];
  assign Delay5_reg_next[45] = Delay5_reg[44];
  assign Delay5_reg_next[46] = Delay5_reg[45];
  assign Delay5_reg_next[47] = Delay5_reg[46];
  assign Delay5_reg_next[48] = Delay5_reg[47];
  assign Delay5_reg_next[49] = Delay5_reg[48];
  assign Delay5_reg_next[50] = Delay5_reg[49];
  assign Delay5_reg_next[51] = Delay5_reg[50];
  assign Delay5_reg_next[52] = Delay5_reg[51];
  assign Delay5_reg_next[53] = Delay5_reg[52];
  assign Delay5_reg_next[54] = Delay5_reg[53];
  assign Delay5_reg_next[55] = Delay5_reg[54];
  assign Delay5_reg_next[56] = Delay5_reg[55];
  assign Delay5_reg_next[57] = Delay5_reg[56];
  assign Delay5_reg_next[58] = Delay5_reg[57];
  assign Delay5_reg_next[59] = Delay5_reg[58];
  assign Delay5_reg_next[60] = Delay5_reg[59];
  assign Delay5_reg_next[61] = Delay5_reg[60];
  assign Delay5_reg_next[62] = Delay5_reg[61];
  assign Delay5_reg_next[63] = Delay5_reg[62];
  assign Delay5_reg_next[64] = Delay5_reg[63];
  assign Delay5_reg_next[65] = Delay5_reg[64];
  assign Delay5_reg_next[66] = Delay5_reg[65];
  assign Delay5_reg_next[67] = Delay5_reg[66];
  assign Delay5_reg_next[68] = Delay5_reg[67];
  assign Delay5_reg_next[69] = Delay5_reg[68];
  assign Delay5_reg_next[70] = Delay5_reg[69];
  assign Delay5_reg_next[71] = Delay5_reg[70];
  assign Delay5_reg_next[72] = Delay5_reg[71];
  assign Delay5_reg_next[73] = Delay5_reg[72];
  assign Delay5_reg_next[74] = Delay5_reg[73];
  assign Delay5_reg_next[75] = Delay5_reg[74];
  assign Delay5_reg_next[76] = Delay5_reg[75];
  assign Delay5_reg_next[77] = Delay5_reg[76];
  assign Delay5_reg_next[78] = Delay5_reg[77];
  assign Delay5_reg_next[79] = Delay5_reg[78];
  assign Delay5_reg_next[80] = Delay5_reg[79];
  assign Delay5_reg_next[81] = Delay5_reg[80];
  assign Delay5_reg_next[82] = Delay5_reg[81];
  assign Delay5_reg_next[83] = Delay5_reg[82];
  assign Delay5_reg_next[84] = Delay5_reg[83];
  assign Delay5_reg_next[85] = Delay5_reg[84];
  assign Delay5_reg_next[86] = Delay5_reg[85];
  assign Delay5_reg_next[87] = Delay5_reg[86];
  assign Delay5_reg_next[88] = Delay5_reg[87];
  assign Delay5_reg_next[89] = Delay5_reg[88];
  assign Delay5_reg_next[90] = Delay5_reg[89];
  assign Delay5_reg_next[91] = Delay5_reg[90];
  assign Delay5_reg_next[92] = Delay5_reg[91];
  assign Delay5_reg_next[93] = Delay5_reg[92];
  assign Delay5_reg_next[94] = Delay5_reg[93];
  assign Delay5_reg_next[95] = Delay5_reg[94];
  assign Delay5_reg_next[96] = Delay5_reg[95];
  assign Delay5_reg_next[97] = Delay5_reg[96];
  assign Delay5_reg_next[98] = Delay5_reg[97];
  assign Delay5_reg_next[99] = Delay5_reg[98];
  assign Delay5_reg_next[100] = Delay5_reg[99];
  assign Delay5_reg_next[101] = Delay5_reg[100];
  assign Delay5_reg_next[102] = Delay5_reg[101];
  assign Delay5_reg_next[103] = Delay5_reg[102];
  assign Delay5_reg_next[104] = Delay5_reg[103];
  assign Delay5_reg_next[105] = Delay5_reg[104];
  assign Delay5_reg_next[106] = Delay5_reg[105];
  assign Delay5_reg_next[107] = Delay5_reg[106];
  assign Delay5_reg_next[108] = Delay5_reg[107];
  assign Delay5_reg_next[109] = Delay5_reg[108];
  assign Delay5_reg_next[110] = Delay5_reg[109];
  assign Delay5_reg_next[111] = Delay5_reg[110];
  assign Delay5_reg_next[112] = Delay5_reg[111];
  assign Delay5_reg_next[113] = Delay5_reg[112];
  assign Delay5_reg_next[114] = Delay5_reg[113];
  assign Delay5_reg_next[115] = Delay5_reg[114];
  assign Delay5_reg_next[116] = Delay5_reg[115];
  assign Delay5_reg_next[117] = Delay5_reg[116];
  assign Delay5_reg_next[118] = Delay5_reg[117];
  assign Delay5_reg_next[119] = Delay5_reg[118];
  assign Delay5_reg_next[120] = Delay5_reg[119];
  assign Delay5_reg_next[121] = Delay5_reg[120];
  assign Delay5_reg_next[122] = Delay5_reg[121];
  assign Delay5_reg_next[123] = Delay5_reg[122];
  assign Delay5_reg_next[124] = Delay5_reg[123];
  assign Delay5_reg_next[125] = Delay5_reg[124];
  assign Delay5_reg_next[126] = Delay5_reg[125];
  assign Delay5_reg_next[127] = Delay5_reg[126];
  assign Delay5_reg_next[128] = Delay5_reg[127];
  assign Delay5_reg_next[129] = Delay5_reg[128];
  assign Delay5_reg_next[130] = Delay5_reg[129];
  assign Delay5_reg_next[131] = Delay5_reg[130];
  assign Delay5_reg_next[132] = Delay5_reg[131];
  assign Delay5_reg_next[133] = Delay5_reg[132];
  assign Delay5_reg_next[134] = Delay5_reg[133];
  assign Delay5_reg_next[135] = Delay5_reg[134];
  assign Delay5_reg_next[136] = Delay5_reg[135];
  assign Delay5_reg_next[137] = Delay5_reg[136];
  assign Delay5_reg_next[138] = Delay5_reg[137];
  assign Delay5_reg_next[139] = Delay5_reg[138];
  assign Delay5_reg_next[140] = Delay5_reg[139];
  assign Delay5_reg_next[141] = Delay5_reg[140];
  assign Delay5_reg_next[142] = Delay5_reg[141];
  assign Delay5_reg_next[143] = Delay5_reg[142];
  assign Delay5_reg_next[144] = Delay5_reg[143];
  assign Delay5_reg_next[145] = Delay5_reg[144];
  assign Delay5_reg_next[146] = Delay5_reg[145];
  assign Delay5_reg_next[147] = Delay5_reg[146];
  assign Delay5_reg_next[148] = Delay5_reg[147];
  assign Delay5_reg_next[149] = Delay5_reg[148];
  assign Delay5_reg_next[150] = Delay5_reg[149];
  assign Delay5_reg_next[151] = Delay5_reg[150];
  assign Delay5_reg_next[152] = Delay5_reg[151];
  assign Delay5_reg_next[153] = Delay5_reg[152];
  assign Delay5_reg_next[154] = Delay5_reg[153];
  assign Delay5_reg_next[155] = Delay5_reg[154];
  assign Delay5_reg_next[156] = Delay5_reg[155];
  assign Delay5_reg_next[157] = Delay5_reg[156];
  assign Delay5_reg_next[158] = Delay5_reg[157];
  assign Delay5_reg_next[159] = Delay5_reg[158];
  assign Delay5_reg_next[160] = Delay5_reg[159];
  assign Delay5_reg_next[161] = Delay5_reg[160];
  assign Delay5_reg_next[162] = Delay5_reg[161];
  assign Delay5_reg_next[163] = Delay5_reg[162];
  assign Delay5_reg_next[164] = Delay5_reg[163];
  assign Delay5_reg_next[165] = Delay5_reg[164];
  assign Delay5_reg_next[166] = Delay5_reg[165];
  assign Delay5_reg_next[167] = Delay5_reg[166];
  assign Delay5_reg_next[168] = Delay5_reg[167];
  assign Delay5_reg_next[169] = Delay5_reg[168];
  assign Delay5_reg_next[170] = Delay5_reg[169];
  assign Delay5_reg_next[171] = Delay5_reg[170];
  assign Delay5_reg_next[172] = Delay5_reg[171];
  assign Delay5_reg_next[173] = Delay5_reg[172];
  assign Delay5_reg_next[174] = Delay5_reg[173];
  assign Delay5_reg_next[175] = Delay5_reg[174];
  assign Delay5_reg_next[176] = Delay5_reg[175];
  assign Delay5_reg_next[177] = Delay5_reg[176];
  assign Delay5_reg_next[178] = Delay5_reg[177];
  assign Delay5_reg_next[179] = Delay5_reg[178];
  assign Delay5_reg_next[180] = Delay5_reg[179];
  assign Delay5_reg_next[181] = Delay5_reg[180];
  assign Delay5_reg_next[182] = Delay5_reg[181];
  assign Delay5_reg_next[183] = Delay5_reg[182];
  assign Delay5_reg_next[184] = Delay5_reg[183];
  assign Delay5_reg_next[185] = Delay5_reg[184];
  assign Delay5_reg_next[186] = Delay5_reg[185];
  assign Delay5_reg_next[187] = Delay5_reg[186];
  assign Delay5_reg_next[188] = Delay5_reg[187];
  assign Delay5_reg_next[189] = Delay5_reg[188];
  assign Delay5_reg_next[190] = Delay5_reg[189];
  assign Delay5_reg_next[191] = Delay5_reg[190];
  assign Delay5_reg_next[192] = Delay5_reg[191];
  assign Delay5_reg_next[193] = Delay5_reg[192];
  assign Delay5_reg_next[194] = Delay5_reg[193];
  assign Delay5_reg_next[195] = Delay5_reg[194];
  assign Delay5_reg_next[196] = Delay5_reg[195];
  assign Delay5_reg_next[197] = Delay5_reg[196];
  assign Delay5_reg_next[198] = Delay5_reg[197];
  assign Delay5_reg_next[199] = Delay5_reg[198];
  assign Delay5_reg_next[200] = Delay5_reg[199];
  assign Delay5_reg_next[201] = Delay5_reg[200];
  assign Delay5_reg_next[202] = Delay5_reg[201];



  assign CUT_NT_NG_out1 = CUT_NT_NG_op_stage1 + Delay5_out1;



  always @(posedge clk or posedge reset)
    begin : Delay10_process
      if (reset == 1'b1) begin
        Delay10_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay10_out1 <= CUT_NT_NG_out1;
        end
      end
    end



  assign Add_out1 = Delay9_out1 - Delay10_out1;



  always @(posedge clk or posedge reset)
    begin : Delay12_process
      if (reset == 1'b1) begin
        Delay12_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay12_out1 <= Add_out1;
        end
      end
    end



  assign switch_compare_1 = Delay12_out1 >= 16'sb0000000000000000;



  always @(posedge clk or posedge reset)
    begin : PreviousLag1_process
      if (reset == 1'b1) begin
        PreviousLag1_reg[0] <= 34'sh000000000;
        PreviousLag1_reg[1] <= 34'sh000000000;
        PreviousLag1_reg[2] <= 34'sh000000000;
        PreviousLag1_reg[3] <= 34'sh000000000;
        PreviousLag1_reg[4] <= 34'sh000000000;
        PreviousLag1_reg[5] <= 34'sh000000000;
        PreviousLag1_reg[6] <= 34'sh000000000;
        PreviousLag1_reg[7] <= 34'sh000000000;
        PreviousLag1_reg[8] <= 34'sh000000000;
        PreviousLag1_reg[9] <= 34'sh000000000;
        PreviousLag1_reg[10] <= 34'sh000000000;
        PreviousLag1_reg[11] <= 34'sh000000000;
        PreviousLag1_reg[12] <= 34'sh000000000;
        PreviousLag1_reg[13] <= 34'sh000000000;
        PreviousLag1_reg[14] <= 34'sh000000000;
        PreviousLag1_reg[15] <= 34'sh000000000;
        PreviousLag1_reg[16] <= 34'sh000000000;
        PreviousLag1_reg[17] <= 34'sh000000000;
        PreviousLag1_reg[18] <= 34'sh000000000;
        PreviousLag1_reg[19] <= 34'sh000000000;
        PreviousLag1_reg[20] <= 34'sh000000000;
        PreviousLag1_reg[21] <= 34'sh000000000;
        PreviousLag1_reg[22] <= 34'sh000000000;
        PreviousLag1_reg[23] <= 34'sh000000000;
        PreviousLag1_reg[24] <= 34'sh000000000;
        PreviousLag1_reg[25] <= 34'sh000000000;
        PreviousLag1_reg[26] <= 34'sh000000000;
        PreviousLag1_reg[27] <= 34'sh000000000;
        PreviousLag1_reg[28] <= 34'sh000000000;
        PreviousLag1_reg[29] <= 34'sh000000000;
        PreviousLag1_reg[30] <= 34'sh000000000;
        PreviousLag1_reg[31] <= 34'sh000000000;
        PreviousLag1_reg[32] <= 34'sh000000000;
        PreviousLag1_reg[33] <= 34'sh000000000;
        PreviousLag1_reg[34] <= 34'sh000000000;
        PreviousLag1_reg[35] <= 34'sh000000000;
        PreviousLag1_reg[36] <= 34'sh000000000;
        PreviousLag1_reg[37] <= 34'sh000000000;
        PreviousLag1_reg[38] <= 34'sh000000000;
        PreviousLag1_reg[39] <= 34'sh000000000;
        PreviousLag1_reg[40] <= 34'sh000000000;
        PreviousLag1_reg[41] <= 34'sh000000000;
        PreviousLag1_reg[42] <= 34'sh000000000;
        PreviousLag1_reg[43] <= 34'sh000000000;
        PreviousLag1_reg[44] <= 34'sh000000000;
        PreviousLag1_reg[45] <= 34'sh000000000;
        PreviousLag1_reg[46] <= 34'sh000000000;
        PreviousLag1_reg[47] <= 34'sh000000000;
        PreviousLag1_reg[48] <= 34'sh000000000;
        PreviousLag1_reg[49] <= 34'sh000000000;
        PreviousLag1_reg[50] <= 34'sh000000000;
        PreviousLag1_reg[51] <= 34'sh000000000;
        PreviousLag1_reg[52] <= 34'sh000000000;
        PreviousLag1_reg[53] <= 34'sh000000000;
        PreviousLag1_reg[54] <= 34'sh000000000;
        PreviousLag1_reg[55] <= 34'sh000000000;
        PreviousLag1_reg[56] <= 34'sh000000000;
        PreviousLag1_reg[57] <= 34'sh000000000;
        PreviousLag1_reg[58] <= 34'sh000000000;
        PreviousLag1_reg[59] <= 34'sh000000000;
        PreviousLag1_reg[60] <= 34'sh000000000;
        PreviousLag1_reg[61] <= 34'sh000000000;
        PreviousLag1_reg[62] <= 34'sh000000000;
        PreviousLag1_reg[63] <= 34'sh000000000;
        PreviousLag1_reg[64] <= 34'sh000000000;
        PreviousLag1_reg[65] <= 34'sh000000000;
        PreviousLag1_reg[66] <= 34'sh000000000;
        PreviousLag1_reg[67] <= 34'sh000000000;
        PreviousLag1_reg[68] <= 34'sh000000000;
        PreviousLag1_reg[69] <= 34'sh000000000;
        PreviousLag1_reg[70] <= 34'sh000000000;
        PreviousLag1_reg[71] <= 34'sh000000000;
        PreviousLag1_reg[72] <= 34'sh000000000;
        PreviousLag1_reg[73] <= 34'sh000000000;
        PreviousLag1_reg[74] <= 34'sh000000000;
        PreviousLag1_reg[75] <= 34'sh000000000;
        PreviousLag1_reg[76] <= 34'sh000000000;
        PreviousLag1_reg[77] <= 34'sh000000000;
        PreviousLag1_reg[78] <= 34'sh000000000;
        PreviousLag1_reg[79] <= 34'sh000000000;
        PreviousLag1_reg[80] <= 34'sh000000000;
        PreviousLag1_reg[81] <= 34'sh000000000;
        PreviousLag1_reg[82] <= 34'sh000000000;
        PreviousLag1_reg[83] <= 34'sh000000000;
        PreviousLag1_reg[84] <= 34'sh000000000;
        PreviousLag1_reg[85] <= 34'sh000000000;
        PreviousLag1_reg[86] <= 34'sh000000000;
        PreviousLag1_reg[87] <= 34'sh000000000;
        PreviousLag1_reg[88] <= 34'sh000000000;
        PreviousLag1_reg[89] <= 34'sh000000000;
        PreviousLag1_reg[90] <= 34'sh000000000;
        PreviousLag1_reg[91] <= 34'sh000000000;
        PreviousLag1_reg[92] <= 34'sh000000000;
        PreviousLag1_reg[93] <= 34'sh000000000;
        PreviousLag1_reg[94] <= 34'sh000000000;
        PreviousLag1_reg[95] <= 34'sh000000000;
        PreviousLag1_reg[96] <= 34'sh000000000;
        PreviousLag1_reg[97] <= 34'sh000000000;
        PreviousLag1_reg[98] <= 34'sh000000000;
        PreviousLag1_reg[99] <= 34'sh000000000;
        PreviousLag1_reg[100] <= 34'sh000000000;
        PreviousLag1_reg[101] <= 34'sh000000000;
        PreviousLag1_reg[102] <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          PreviousLag1_reg[0] <= PreviousLag1_reg_next[0];
          PreviousLag1_reg[1] <= PreviousLag1_reg_next[1];
          PreviousLag1_reg[2] <= PreviousLag1_reg_next[2];
          PreviousLag1_reg[3] <= PreviousLag1_reg_next[3];
          PreviousLag1_reg[4] <= PreviousLag1_reg_next[4];
          PreviousLag1_reg[5] <= PreviousLag1_reg_next[5];
          PreviousLag1_reg[6] <= PreviousLag1_reg_next[6];
          PreviousLag1_reg[7] <= PreviousLag1_reg_next[7];
          PreviousLag1_reg[8] <= PreviousLag1_reg_next[8];
          PreviousLag1_reg[9] <= PreviousLag1_reg_next[9];
          PreviousLag1_reg[10] <= PreviousLag1_reg_next[10];
          PreviousLag1_reg[11] <= PreviousLag1_reg_next[11];
          PreviousLag1_reg[12] <= PreviousLag1_reg_next[12];
          PreviousLag1_reg[13] <= PreviousLag1_reg_next[13];
          PreviousLag1_reg[14] <= PreviousLag1_reg_next[14];
          PreviousLag1_reg[15] <= PreviousLag1_reg_next[15];
          PreviousLag1_reg[16] <= PreviousLag1_reg_next[16];
          PreviousLag1_reg[17] <= PreviousLag1_reg_next[17];
          PreviousLag1_reg[18] <= PreviousLag1_reg_next[18];
          PreviousLag1_reg[19] <= PreviousLag1_reg_next[19];
          PreviousLag1_reg[20] <= PreviousLag1_reg_next[20];
          PreviousLag1_reg[21] <= PreviousLag1_reg_next[21];
          PreviousLag1_reg[22] <= PreviousLag1_reg_next[22];
          PreviousLag1_reg[23] <= PreviousLag1_reg_next[23];
          PreviousLag1_reg[24] <= PreviousLag1_reg_next[24];
          PreviousLag1_reg[25] <= PreviousLag1_reg_next[25];
          PreviousLag1_reg[26] <= PreviousLag1_reg_next[26];
          PreviousLag1_reg[27] <= PreviousLag1_reg_next[27];
          PreviousLag1_reg[28] <= PreviousLag1_reg_next[28];
          PreviousLag1_reg[29] <= PreviousLag1_reg_next[29];
          PreviousLag1_reg[30] <= PreviousLag1_reg_next[30];
          PreviousLag1_reg[31] <= PreviousLag1_reg_next[31];
          PreviousLag1_reg[32] <= PreviousLag1_reg_next[32];
          PreviousLag1_reg[33] <= PreviousLag1_reg_next[33];
          PreviousLag1_reg[34] <= PreviousLag1_reg_next[34];
          PreviousLag1_reg[35] <= PreviousLag1_reg_next[35];
          PreviousLag1_reg[36] <= PreviousLag1_reg_next[36];
          PreviousLag1_reg[37] <= PreviousLag1_reg_next[37];
          PreviousLag1_reg[38] <= PreviousLag1_reg_next[38];
          PreviousLag1_reg[39] <= PreviousLag1_reg_next[39];
          PreviousLag1_reg[40] <= PreviousLag1_reg_next[40];
          PreviousLag1_reg[41] <= PreviousLag1_reg_next[41];
          PreviousLag1_reg[42] <= PreviousLag1_reg_next[42];
          PreviousLag1_reg[43] <= PreviousLag1_reg_next[43];
          PreviousLag1_reg[44] <= PreviousLag1_reg_next[44];
          PreviousLag1_reg[45] <= PreviousLag1_reg_next[45];
          PreviousLag1_reg[46] <= PreviousLag1_reg_next[46];
          PreviousLag1_reg[47] <= PreviousLag1_reg_next[47];
          PreviousLag1_reg[48] <= PreviousLag1_reg_next[48];
          PreviousLag1_reg[49] <= PreviousLag1_reg_next[49];
          PreviousLag1_reg[50] <= PreviousLag1_reg_next[50];
          PreviousLag1_reg[51] <= PreviousLag1_reg_next[51];
          PreviousLag1_reg[52] <= PreviousLag1_reg_next[52];
          PreviousLag1_reg[53] <= PreviousLag1_reg_next[53];
          PreviousLag1_reg[54] <= PreviousLag1_reg_next[54];
          PreviousLag1_reg[55] <= PreviousLag1_reg_next[55];
          PreviousLag1_reg[56] <= PreviousLag1_reg_next[56];
          PreviousLag1_reg[57] <= PreviousLag1_reg_next[57];
          PreviousLag1_reg[58] <= PreviousLag1_reg_next[58];
          PreviousLag1_reg[59] <= PreviousLag1_reg_next[59];
          PreviousLag1_reg[60] <= PreviousLag1_reg_next[60];
          PreviousLag1_reg[61] <= PreviousLag1_reg_next[61];
          PreviousLag1_reg[62] <= PreviousLag1_reg_next[62];
          PreviousLag1_reg[63] <= PreviousLag1_reg_next[63];
          PreviousLag1_reg[64] <= PreviousLag1_reg_next[64];
          PreviousLag1_reg[65] <= PreviousLag1_reg_next[65];
          PreviousLag1_reg[66] <= PreviousLag1_reg_next[66];
          PreviousLag1_reg[67] <= PreviousLag1_reg_next[67];
          PreviousLag1_reg[68] <= PreviousLag1_reg_next[68];
          PreviousLag1_reg[69] <= PreviousLag1_reg_next[69];
          PreviousLag1_reg[70] <= PreviousLag1_reg_next[70];
          PreviousLag1_reg[71] <= PreviousLag1_reg_next[71];
          PreviousLag1_reg[72] <= PreviousLag1_reg_next[72];
          PreviousLag1_reg[73] <= PreviousLag1_reg_next[73];
          PreviousLag1_reg[74] <= PreviousLag1_reg_next[74];
          PreviousLag1_reg[75] <= PreviousLag1_reg_next[75];
          PreviousLag1_reg[76] <= PreviousLag1_reg_next[76];
          PreviousLag1_reg[77] <= PreviousLag1_reg_next[77];
          PreviousLag1_reg[78] <= PreviousLag1_reg_next[78];
          PreviousLag1_reg[79] <= PreviousLag1_reg_next[79];
          PreviousLag1_reg[80] <= PreviousLag1_reg_next[80];
          PreviousLag1_reg[81] <= PreviousLag1_reg_next[81];
          PreviousLag1_reg[82] <= PreviousLag1_reg_next[82];
          PreviousLag1_reg[83] <= PreviousLag1_reg_next[83];
          PreviousLag1_reg[84] <= PreviousLag1_reg_next[84];
          PreviousLag1_reg[85] <= PreviousLag1_reg_next[85];
          PreviousLag1_reg[86] <= PreviousLag1_reg_next[86];
          PreviousLag1_reg[87] <= PreviousLag1_reg_next[87];
          PreviousLag1_reg[88] <= PreviousLag1_reg_next[88];
          PreviousLag1_reg[89] <= PreviousLag1_reg_next[89];
          PreviousLag1_reg[90] <= PreviousLag1_reg_next[90];
          PreviousLag1_reg[91] <= PreviousLag1_reg_next[91];
          PreviousLag1_reg[92] <= PreviousLag1_reg_next[92];
          PreviousLag1_reg[93] <= PreviousLag1_reg_next[93];
          PreviousLag1_reg[94] <= PreviousLag1_reg_next[94];
          PreviousLag1_reg[95] <= PreviousLag1_reg_next[95];
          PreviousLag1_reg[96] <= PreviousLag1_reg_next[96];
          PreviousLag1_reg[97] <= PreviousLag1_reg_next[97];
          PreviousLag1_reg[98] <= PreviousLag1_reg_next[98];
          PreviousLag1_reg[99] <= PreviousLag1_reg_next[99];
          PreviousLag1_reg[100] <= PreviousLag1_reg_next[100];
          PreviousLag1_reg[101] <= PreviousLag1_reg_next[101];
          PreviousLag1_reg[102] <= PreviousLag1_reg_next[102];
        end
      end
    end

  assign PreviousLag1_out1 = PreviousLag1_reg[102];
  assign PreviousLag1_reg_next[0] = Lag_Delay;
  assign PreviousLag1_reg_next[1] = PreviousLag1_reg[0];
  assign PreviousLag1_reg_next[2] = PreviousLag1_reg[1];
  assign PreviousLag1_reg_next[3] = PreviousLag1_reg[2];
  assign PreviousLag1_reg_next[4] = PreviousLag1_reg[3];
  assign PreviousLag1_reg_next[5] = PreviousLag1_reg[4];
  assign PreviousLag1_reg_next[6] = PreviousLag1_reg[5];
  assign PreviousLag1_reg_next[7] = PreviousLag1_reg[6];
  assign PreviousLag1_reg_next[8] = PreviousLag1_reg[7];
  assign PreviousLag1_reg_next[9] = PreviousLag1_reg[8];
  assign PreviousLag1_reg_next[10] = PreviousLag1_reg[9];
  assign PreviousLag1_reg_next[11] = PreviousLag1_reg[10];
  assign PreviousLag1_reg_next[12] = PreviousLag1_reg[11];
  assign PreviousLag1_reg_next[13] = PreviousLag1_reg[12];
  assign PreviousLag1_reg_next[14] = PreviousLag1_reg[13];
  assign PreviousLag1_reg_next[15] = PreviousLag1_reg[14];
  assign PreviousLag1_reg_next[16] = PreviousLag1_reg[15];
  assign PreviousLag1_reg_next[17] = PreviousLag1_reg[16];
  assign PreviousLag1_reg_next[18] = PreviousLag1_reg[17];
  assign PreviousLag1_reg_next[19] = PreviousLag1_reg[18];
  assign PreviousLag1_reg_next[20] = PreviousLag1_reg[19];
  assign PreviousLag1_reg_next[21] = PreviousLag1_reg[20];
  assign PreviousLag1_reg_next[22] = PreviousLag1_reg[21];
  assign PreviousLag1_reg_next[23] = PreviousLag1_reg[22];
  assign PreviousLag1_reg_next[24] = PreviousLag1_reg[23];
  assign PreviousLag1_reg_next[25] = PreviousLag1_reg[24];
  assign PreviousLag1_reg_next[26] = PreviousLag1_reg[25];
  assign PreviousLag1_reg_next[27] = PreviousLag1_reg[26];
  assign PreviousLag1_reg_next[28] = PreviousLag1_reg[27];
  assign PreviousLag1_reg_next[29] = PreviousLag1_reg[28];
  assign PreviousLag1_reg_next[30] = PreviousLag1_reg[29];
  assign PreviousLag1_reg_next[31] = PreviousLag1_reg[30];
  assign PreviousLag1_reg_next[32] = PreviousLag1_reg[31];
  assign PreviousLag1_reg_next[33] = PreviousLag1_reg[32];
  assign PreviousLag1_reg_next[34] = PreviousLag1_reg[33];
  assign PreviousLag1_reg_next[35] = PreviousLag1_reg[34];
  assign PreviousLag1_reg_next[36] = PreviousLag1_reg[35];
  assign PreviousLag1_reg_next[37] = PreviousLag1_reg[36];
  assign PreviousLag1_reg_next[38] = PreviousLag1_reg[37];
  assign PreviousLag1_reg_next[39] = PreviousLag1_reg[38];
  assign PreviousLag1_reg_next[40] = PreviousLag1_reg[39];
  assign PreviousLag1_reg_next[41] = PreviousLag1_reg[40];
  assign PreviousLag1_reg_next[42] = PreviousLag1_reg[41];
  assign PreviousLag1_reg_next[43] = PreviousLag1_reg[42];
  assign PreviousLag1_reg_next[44] = PreviousLag1_reg[43];
  assign PreviousLag1_reg_next[45] = PreviousLag1_reg[44];
  assign PreviousLag1_reg_next[46] = PreviousLag1_reg[45];
  assign PreviousLag1_reg_next[47] = PreviousLag1_reg[46];
  assign PreviousLag1_reg_next[48] = PreviousLag1_reg[47];
  assign PreviousLag1_reg_next[49] = PreviousLag1_reg[48];
  assign PreviousLag1_reg_next[50] = PreviousLag1_reg[49];
  assign PreviousLag1_reg_next[51] = PreviousLag1_reg[50];
  assign PreviousLag1_reg_next[52] = PreviousLag1_reg[51];
  assign PreviousLag1_reg_next[53] = PreviousLag1_reg[52];
  assign PreviousLag1_reg_next[54] = PreviousLag1_reg[53];
  assign PreviousLag1_reg_next[55] = PreviousLag1_reg[54];
  assign PreviousLag1_reg_next[56] = PreviousLag1_reg[55];
  assign PreviousLag1_reg_next[57] = PreviousLag1_reg[56];
  assign PreviousLag1_reg_next[58] = PreviousLag1_reg[57];
  assign PreviousLag1_reg_next[59] = PreviousLag1_reg[58];
  assign PreviousLag1_reg_next[60] = PreviousLag1_reg[59];
  assign PreviousLag1_reg_next[61] = PreviousLag1_reg[60];
  assign PreviousLag1_reg_next[62] = PreviousLag1_reg[61];
  assign PreviousLag1_reg_next[63] = PreviousLag1_reg[62];
  assign PreviousLag1_reg_next[64] = PreviousLag1_reg[63];
  assign PreviousLag1_reg_next[65] = PreviousLag1_reg[64];
  assign PreviousLag1_reg_next[66] = PreviousLag1_reg[65];
  assign PreviousLag1_reg_next[67] = PreviousLag1_reg[66];
  assign PreviousLag1_reg_next[68] = PreviousLag1_reg[67];
  assign PreviousLag1_reg_next[69] = PreviousLag1_reg[68];
  assign PreviousLag1_reg_next[70] = PreviousLag1_reg[69];
  assign PreviousLag1_reg_next[71] = PreviousLag1_reg[70];
  assign PreviousLag1_reg_next[72] = PreviousLag1_reg[71];
  assign PreviousLag1_reg_next[73] = PreviousLag1_reg[72];
  assign PreviousLag1_reg_next[74] = PreviousLag1_reg[73];
  assign PreviousLag1_reg_next[75] = PreviousLag1_reg[74];
  assign PreviousLag1_reg_next[76] = PreviousLag1_reg[75];
  assign PreviousLag1_reg_next[77] = PreviousLag1_reg[76];
  assign PreviousLag1_reg_next[78] = PreviousLag1_reg[77];
  assign PreviousLag1_reg_next[79] = PreviousLag1_reg[78];
  assign PreviousLag1_reg_next[80] = PreviousLag1_reg[79];
  assign PreviousLag1_reg_next[81] = PreviousLag1_reg[80];
  assign PreviousLag1_reg_next[82] = PreviousLag1_reg[81];
  assign PreviousLag1_reg_next[83] = PreviousLag1_reg[82];
  assign PreviousLag1_reg_next[84] = PreviousLag1_reg[83];
  assign PreviousLag1_reg_next[85] = PreviousLag1_reg[84];
  assign PreviousLag1_reg_next[86] = PreviousLag1_reg[85];
  assign PreviousLag1_reg_next[87] = PreviousLag1_reg[86];
  assign PreviousLag1_reg_next[88] = PreviousLag1_reg[87];
  assign PreviousLag1_reg_next[89] = PreviousLag1_reg[88];
  assign PreviousLag1_reg_next[90] = PreviousLag1_reg[89];
  assign PreviousLag1_reg_next[91] = PreviousLag1_reg[90];
  assign PreviousLag1_reg_next[92] = PreviousLag1_reg[91];
  assign PreviousLag1_reg_next[93] = PreviousLag1_reg[92];
  assign PreviousLag1_reg_next[94] = PreviousLag1_reg[93];
  assign PreviousLag1_reg_next[95] = PreviousLag1_reg[94];
  assign PreviousLag1_reg_next[96] = PreviousLag1_reg[95];
  assign PreviousLag1_reg_next[97] = PreviousLag1_reg[96];
  assign PreviousLag1_reg_next[98] = PreviousLag1_reg[97];
  assign PreviousLag1_reg_next[99] = PreviousLag1_reg[98];
  assign PreviousLag1_reg_next[100] = PreviousLag1_reg[99];
  assign PreviousLag1_reg_next[101] = PreviousLag1_reg[100];
  assign PreviousLag1_reg_next[102] = PreviousLag1_reg[101];



  assign alpha_out1_2 = 34'sh000000000;



  assign Compare_to_0_out1 = (switch_compare_1 == 1'b0 ? PreviousLag1_out1 :
              alpha_out1_2);



  always @(posedge clk or posedge reset)
    begin : Delay14_process
      if (reset == 1'b1) begin
        Delay14_out1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay14_out1 <= Compare_to_0_out1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : PreviousLag2_process
      if (reset == 1'b1) begin
        PreviousLag2_reg[0] <= 34'sh000000000;
        PreviousLag2_reg[1] <= 34'sh000000000;
        PreviousLag2_reg[2] <= 34'sh000000000;
        PreviousLag2_reg[3] <= 34'sh000000000;
        PreviousLag2_reg[4] <= 34'sh000000000;
        PreviousLag2_reg[5] <= 34'sh000000000;
        PreviousLag2_reg[6] <= 34'sh000000000;
        PreviousLag2_reg[7] <= 34'sh000000000;
        PreviousLag2_reg[8] <= 34'sh000000000;
        PreviousLag2_reg[9] <= 34'sh000000000;
        PreviousLag2_reg[10] <= 34'sh000000000;
        PreviousLag2_reg[11] <= 34'sh000000000;
        PreviousLag2_reg[12] <= 34'sh000000000;
        PreviousLag2_reg[13] <= 34'sh000000000;
        PreviousLag2_reg[14] <= 34'sh000000000;
        PreviousLag2_reg[15] <= 34'sh000000000;
        PreviousLag2_reg[16] <= 34'sh000000000;
        PreviousLag2_reg[17] <= 34'sh000000000;
        PreviousLag2_reg[18] <= 34'sh000000000;
        PreviousLag2_reg[19] <= 34'sh000000000;
        PreviousLag2_reg[20] <= 34'sh000000000;
        PreviousLag2_reg[21] <= 34'sh000000000;
        PreviousLag2_reg[22] <= 34'sh000000000;
        PreviousLag2_reg[23] <= 34'sh000000000;
        PreviousLag2_reg[24] <= 34'sh000000000;
        PreviousLag2_reg[25] <= 34'sh000000000;
        PreviousLag2_reg[26] <= 34'sh000000000;
        PreviousLag2_reg[27] <= 34'sh000000000;
        PreviousLag2_reg[28] <= 34'sh000000000;
        PreviousLag2_reg[29] <= 34'sh000000000;
        PreviousLag2_reg[30] <= 34'sh000000000;
        PreviousLag2_reg[31] <= 34'sh000000000;
        PreviousLag2_reg[32] <= 34'sh000000000;
        PreviousLag2_reg[33] <= 34'sh000000000;
        PreviousLag2_reg[34] <= 34'sh000000000;
        PreviousLag2_reg[35] <= 34'sh000000000;
        PreviousLag2_reg[36] <= 34'sh000000000;
        PreviousLag2_reg[37] <= 34'sh000000000;
        PreviousLag2_reg[38] <= 34'sh000000000;
        PreviousLag2_reg[39] <= 34'sh000000000;
        PreviousLag2_reg[40] <= 34'sh000000000;
        PreviousLag2_reg[41] <= 34'sh000000000;
        PreviousLag2_reg[42] <= 34'sh000000000;
        PreviousLag2_reg[43] <= 34'sh000000000;
        PreviousLag2_reg[44] <= 34'sh000000000;
        PreviousLag2_reg[45] <= 34'sh000000000;
        PreviousLag2_reg[46] <= 34'sh000000000;
        PreviousLag2_reg[47] <= 34'sh000000000;
        PreviousLag2_reg[48] <= 34'sh000000000;
        PreviousLag2_reg[49] <= 34'sh000000000;
        PreviousLag2_reg[50] <= 34'sh000000000;
        PreviousLag2_reg[51] <= 34'sh000000000;
        PreviousLag2_reg[52] <= 34'sh000000000;
        PreviousLag2_reg[53] <= 34'sh000000000;
        PreviousLag2_reg[54] <= 34'sh000000000;
        PreviousLag2_reg[55] <= 34'sh000000000;
        PreviousLag2_reg[56] <= 34'sh000000000;
        PreviousLag2_reg[57] <= 34'sh000000000;
        PreviousLag2_reg[58] <= 34'sh000000000;
        PreviousLag2_reg[59] <= 34'sh000000000;
        PreviousLag2_reg[60] <= 34'sh000000000;
        PreviousLag2_reg[61] <= 34'sh000000000;
        PreviousLag2_reg[62] <= 34'sh000000000;
        PreviousLag2_reg[63] <= 34'sh000000000;
        PreviousLag2_reg[64] <= 34'sh000000000;
        PreviousLag2_reg[65] <= 34'sh000000000;
        PreviousLag2_reg[66] <= 34'sh000000000;
        PreviousLag2_reg[67] <= 34'sh000000000;
        PreviousLag2_reg[68] <= 34'sh000000000;
        PreviousLag2_reg[69] <= 34'sh000000000;
        PreviousLag2_reg[70] <= 34'sh000000000;
        PreviousLag2_reg[71] <= 34'sh000000000;
        PreviousLag2_reg[72] <= 34'sh000000000;
        PreviousLag2_reg[73] <= 34'sh000000000;
        PreviousLag2_reg[74] <= 34'sh000000000;
        PreviousLag2_reg[75] <= 34'sh000000000;
        PreviousLag2_reg[76] <= 34'sh000000000;
        PreviousLag2_reg[77] <= 34'sh000000000;
        PreviousLag2_reg[78] <= 34'sh000000000;
        PreviousLag2_reg[79] <= 34'sh000000000;
        PreviousLag2_reg[80] <= 34'sh000000000;
        PreviousLag2_reg[81] <= 34'sh000000000;
        PreviousLag2_reg[82] <= 34'sh000000000;
        PreviousLag2_reg[83] <= 34'sh000000000;
        PreviousLag2_reg[84] <= 34'sh000000000;
        PreviousLag2_reg[85] <= 34'sh000000000;
        PreviousLag2_reg[86] <= 34'sh000000000;
        PreviousLag2_reg[87] <= 34'sh000000000;
        PreviousLag2_reg[88] <= 34'sh000000000;
        PreviousLag2_reg[89] <= 34'sh000000000;
        PreviousLag2_reg[90] <= 34'sh000000000;
        PreviousLag2_reg[91] <= 34'sh000000000;
        PreviousLag2_reg[92] <= 34'sh000000000;
        PreviousLag2_reg[93] <= 34'sh000000000;
        PreviousLag2_reg[94] <= 34'sh000000000;
        PreviousLag2_reg[95] <= 34'sh000000000;
        PreviousLag2_reg[96] <= 34'sh000000000;
        PreviousLag2_reg[97] <= 34'sh000000000;
        PreviousLag2_reg[98] <= 34'sh000000000;
        PreviousLag2_reg[99] <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          PreviousLag2_reg[0] <= PreviousLag2_reg_next[0];
          PreviousLag2_reg[1] <= PreviousLag2_reg_next[1];
          PreviousLag2_reg[2] <= PreviousLag2_reg_next[2];
          PreviousLag2_reg[3] <= PreviousLag2_reg_next[3];
          PreviousLag2_reg[4] <= PreviousLag2_reg_next[4];
          PreviousLag2_reg[5] <= PreviousLag2_reg_next[5];
          PreviousLag2_reg[6] <= PreviousLag2_reg_next[6];
          PreviousLag2_reg[7] <= PreviousLag2_reg_next[7];
          PreviousLag2_reg[8] <= PreviousLag2_reg_next[8];
          PreviousLag2_reg[9] <= PreviousLag2_reg_next[9];
          PreviousLag2_reg[10] <= PreviousLag2_reg_next[10];
          PreviousLag2_reg[11] <= PreviousLag2_reg_next[11];
          PreviousLag2_reg[12] <= PreviousLag2_reg_next[12];
          PreviousLag2_reg[13] <= PreviousLag2_reg_next[13];
          PreviousLag2_reg[14] <= PreviousLag2_reg_next[14];
          PreviousLag2_reg[15] <= PreviousLag2_reg_next[15];
          PreviousLag2_reg[16] <= PreviousLag2_reg_next[16];
          PreviousLag2_reg[17] <= PreviousLag2_reg_next[17];
          PreviousLag2_reg[18] <= PreviousLag2_reg_next[18];
          PreviousLag2_reg[19] <= PreviousLag2_reg_next[19];
          PreviousLag2_reg[20] <= PreviousLag2_reg_next[20];
          PreviousLag2_reg[21] <= PreviousLag2_reg_next[21];
          PreviousLag2_reg[22] <= PreviousLag2_reg_next[22];
          PreviousLag2_reg[23] <= PreviousLag2_reg_next[23];
          PreviousLag2_reg[24] <= PreviousLag2_reg_next[24];
          PreviousLag2_reg[25] <= PreviousLag2_reg_next[25];
          PreviousLag2_reg[26] <= PreviousLag2_reg_next[26];
          PreviousLag2_reg[27] <= PreviousLag2_reg_next[27];
          PreviousLag2_reg[28] <= PreviousLag2_reg_next[28];
          PreviousLag2_reg[29] <= PreviousLag2_reg_next[29];
          PreviousLag2_reg[30] <= PreviousLag2_reg_next[30];
          PreviousLag2_reg[31] <= PreviousLag2_reg_next[31];
          PreviousLag2_reg[32] <= PreviousLag2_reg_next[32];
          PreviousLag2_reg[33] <= PreviousLag2_reg_next[33];
          PreviousLag2_reg[34] <= PreviousLag2_reg_next[34];
          PreviousLag2_reg[35] <= PreviousLag2_reg_next[35];
          PreviousLag2_reg[36] <= PreviousLag2_reg_next[36];
          PreviousLag2_reg[37] <= PreviousLag2_reg_next[37];
          PreviousLag2_reg[38] <= PreviousLag2_reg_next[38];
          PreviousLag2_reg[39] <= PreviousLag2_reg_next[39];
          PreviousLag2_reg[40] <= PreviousLag2_reg_next[40];
          PreviousLag2_reg[41] <= PreviousLag2_reg_next[41];
          PreviousLag2_reg[42] <= PreviousLag2_reg_next[42];
          PreviousLag2_reg[43] <= PreviousLag2_reg_next[43];
          PreviousLag2_reg[44] <= PreviousLag2_reg_next[44];
          PreviousLag2_reg[45] <= PreviousLag2_reg_next[45];
          PreviousLag2_reg[46] <= PreviousLag2_reg_next[46];
          PreviousLag2_reg[47] <= PreviousLag2_reg_next[47];
          PreviousLag2_reg[48] <= PreviousLag2_reg_next[48];
          PreviousLag2_reg[49] <= PreviousLag2_reg_next[49];
          PreviousLag2_reg[50] <= PreviousLag2_reg_next[50];
          PreviousLag2_reg[51] <= PreviousLag2_reg_next[51];
          PreviousLag2_reg[52] <= PreviousLag2_reg_next[52];
          PreviousLag2_reg[53] <= PreviousLag2_reg_next[53];
          PreviousLag2_reg[54] <= PreviousLag2_reg_next[54];
          PreviousLag2_reg[55] <= PreviousLag2_reg_next[55];
          PreviousLag2_reg[56] <= PreviousLag2_reg_next[56];
          PreviousLag2_reg[57] <= PreviousLag2_reg_next[57];
          PreviousLag2_reg[58] <= PreviousLag2_reg_next[58];
          PreviousLag2_reg[59] <= PreviousLag2_reg_next[59];
          PreviousLag2_reg[60] <= PreviousLag2_reg_next[60];
          PreviousLag2_reg[61] <= PreviousLag2_reg_next[61];
          PreviousLag2_reg[62] <= PreviousLag2_reg_next[62];
          PreviousLag2_reg[63] <= PreviousLag2_reg_next[63];
          PreviousLag2_reg[64] <= PreviousLag2_reg_next[64];
          PreviousLag2_reg[65] <= PreviousLag2_reg_next[65];
          PreviousLag2_reg[66] <= PreviousLag2_reg_next[66];
          PreviousLag2_reg[67] <= PreviousLag2_reg_next[67];
          PreviousLag2_reg[68] <= PreviousLag2_reg_next[68];
          PreviousLag2_reg[69] <= PreviousLag2_reg_next[69];
          PreviousLag2_reg[70] <= PreviousLag2_reg_next[70];
          PreviousLag2_reg[71] <= PreviousLag2_reg_next[71];
          PreviousLag2_reg[72] <= PreviousLag2_reg_next[72];
          PreviousLag2_reg[73] <= PreviousLag2_reg_next[73];
          PreviousLag2_reg[74] <= PreviousLag2_reg_next[74];
          PreviousLag2_reg[75] <= PreviousLag2_reg_next[75];
          PreviousLag2_reg[76] <= PreviousLag2_reg_next[76];
          PreviousLag2_reg[77] <= PreviousLag2_reg_next[77];
          PreviousLag2_reg[78] <= PreviousLag2_reg_next[78];
          PreviousLag2_reg[79] <= PreviousLag2_reg_next[79];
          PreviousLag2_reg[80] <= PreviousLag2_reg_next[80];
          PreviousLag2_reg[81] <= PreviousLag2_reg_next[81];
          PreviousLag2_reg[82] <= PreviousLag2_reg_next[82];
          PreviousLag2_reg[83] <= PreviousLag2_reg_next[83];
          PreviousLag2_reg[84] <= PreviousLag2_reg_next[84];
          PreviousLag2_reg[85] <= PreviousLag2_reg_next[85];
          PreviousLag2_reg[86] <= PreviousLag2_reg_next[86];
          PreviousLag2_reg[87] <= PreviousLag2_reg_next[87];
          PreviousLag2_reg[88] <= PreviousLag2_reg_next[88];
          PreviousLag2_reg[89] <= PreviousLag2_reg_next[89];
          PreviousLag2_reg[90] <= PreviousLag2_reg_next[90];
          PreviousLag2_reg[91] <= PreviousLag2_reg_next[91];
          PreviousLag2_reg[92] <= PreviousLag2_reg_next[92];
          PreviousLag2_reg[93] <= PreviousLag2_reg_next[93];
          PreviousLag2_reg[94] <= PreviousLag2_reg_next[94];
          PreviousLag2_reg[95] <= PreviousLag2_reg_next[95];
          PreviousLag2_reg[96] <= PreviousLag2_reg_next[96];
          PreviousLag2_reg[97] <= PreviousLag2_reg_next[97];
          PreviousLag2_reg[98] <= PreviousLag2_reg_next[98];
          PreviousLag2_reg[99] <= PreviousLag2_reg_next[99];
        end
      end
    end

  assign PreviousLag2_out1 = PreviousLag2_reg[99];
  assign PreviousLag2_reg_next[0] = Delay14_out1;
  assign PreviousLag2_reg_next[1] = PreviousLag2_reg[0];
  assign PreviousLag2_reg_next[2] = PreviousLag2_reg[1];
  assign PreviousLag2_reg_next[3] = PreviousLag2_reg[2];
  assign PreviousLag2_reg_next[4] = PreviousLag2_reg[3];
  assign PreviousLag2_reg_next[5] = PreviousLag2_reg[4];
  assign PreviousLag2_reg_next[6] = PreviousLag2_reg[5];
  assign PreviousLag2_reg_next[7] = PreviousLag2_reg[6];
  assign PreviousLag2_reg_next[8] = PreviousLag2_reg[7];
  assign PreviousLag2_reg_next[9] = PreviousLag2_reg[8];
  assign PreviousLag2_reg_next[10] = PreviousLag2_reg[9];
  assign PreviousLag2_reg_next[11] = PreviousLag2_reg[10];
  assign PreviousLag2_reg_next[12] = PreviousLag2_reg[11];
  assign PreviousLag2_reg_next[13] = PreviousLag2_reg[12];
  assign PreviousLag2_reg_next[14] = PreviousLag2_reg[13];
  assign PreviousLag2_reg_next[15] = PreviousLag2_reg[14];
  assign PreviousLag2_reg_next[16] = PreviousLag2_reg[15];
  assign PreviousLag2_reg_next[17] = PreviousLag2_reg[16];
  assign PreviousLag2_reg_next[18] = PreviousLag2_reg[17];
  assign PreviousLag2_reg_next[19] = PreviousLag2_reg[18];
  assign PreviousLag2_reg_next[20] = PreviousLag2_reg[19];
  assign PreviousLag2_reg_next[21] = PreviousLag2_reg[20];
  assign PreviousLag2_reg_next[22] = PreviousLag2_reg[21];
  assign PreviousLag2_reg_next[23] = PreviousLag2_reg[22];
  assign PreviousLag2_reg_next[24] = PreviousLag2_reg[23];
  assign PreviousLag2_reg_next[25] = PreviousLag2_reg[24];
  assign PreviousLag2_reg_next[26] = PreviousLag2_reg[25];
  assign PreviousLag2_reg_next[27] = PreviousLag2_reg[26];
  assign PreviousLag2_reg_next[28] = PreviousLag2_reg[27];
  assign PreviousLag2_reg_next[29] = PreviousLag2_reg[28];
  assign PreviousLag2_reg_next[30] = PreviousLag2_reg[29];
  assign PreviousLag2_reg_next[31] = PreviousLag2_reg[30];
  assign PreviousLag2_reg_next[32] = PreviousLag2_reg[31];
  assign PreviousLag2_reg_next[33] = PreviousLag2_reg[32];
  assign PreviousLag2_reg_next[34] = PreviousLag2_reg[33];
  assign PreviousLag2_reg_next[35] = PreviousLag2_reg[34];
  assign PreviousLag2_reg_next[36] = PreviousLag2_reg[35];
  assign PreviousLag2_reg_next[37] = PreviousLag2_reg[36];
  assign PreviousLag2_reg_next[38] = PreviousLag2_reg[37];
  assign PreviousLag2_reg_next[39] = PreviousLag2_reg[38];
  assign PreviousLag2_reg_next[40] = PreviousLag2_reg[39];
  assign PreviousLag2_reg_next[41] = PreviousLag2_reg[40];
  assign PreviousLag2_reg_next[42] = PreviousLag2_reg[41];
  assign PreviousLag2_reg_next[43] = PreviousLag2_reg[42];
  assign PreviousLag2_reg_next[44] = PreviousLag2_reg[43];
  assign PreviousLag2_reg_next[45] = PreviousLag2_reg[44];
  assign PreviousLag2_reg_next[46] = PreviousLag2_reg[45];
  assign PreviousLag2_reg_next[47] = PreviousLag2_reg[46];
  assign PreviousLag2_reg_next[48] = PreviousLag2_reg[47];
  assign PreviousLag2_reg_next[49] = PreviousLag2_reg[48];
  assign PreviousLag2_reg_next[50] = PreviousLag2_reg[49];
  assign PreviousLag2_reg_next[51] = PreviousLag2_reg[50];
  assign PreviousLag2_reg_next[52] = PreviousLag2_reg[51];
  assign PreviousLag2_reg_next[53] = PreviousLag2_reg[52];
  assign PreviousLag2_reg_next[54] = PreviousLag2_reg[53];
  assign PreviousLag2_reg_next[55] = PreviousLag2_reg[54];
  assign PreviousLag2_reg_next[56] = PreviousLag2_reg[55];
  assign PreviousLag2_reg_next[57] = PreviousLag2_reg[56];
  assign PreviousLag2_reg_next[58] = PreviousLag2_reg[57];
  assign PreviousLag2_reg_next[59] = PreviousLag2_reg[58];
  assign PreviousLag2_reg_next[60] = PreviousLag2_reg[59];
  assign PreviousLag2_reg_next[61] = PreviousLag2_reg[60];
  assign PreviousLag2_reg_next[62] = PreviousLag2_reg[61];
  assign PreviousLag2_reg_next[63] = PreviousLag2_reg[62];
  assign PreviousLag2_reg_next[64] = PreviousLag2_reg[63];
  assign PreviousLag2_reg_next[65] = PreviousLag2_reg[64];
  assign PreviousLag2_reg_next[66] = PreviousLag2_reg[65];
  assign PreviousLag2_reg_next[67] = PreviousLag2_reg[66];
  assign PreviousLag2_reg_next[68] = PreviousLag2_reg[67];
  assign PreviousLag2_reg_next[69] = PreviousLag2_reg[68];
  assign PreviousLag2_reg_next[70] = PreviousLag2_reg[69];
  assign PreviousLag2_reg_next[71] = PreviousLag2_reg[70];
  assign PreviousLag2_reg_next[72] = PreviousLag2_reg[71];
  assign PreviousLag2_reg_next[73] = PreviousLag2_reg[72];
  assign PreviousLag2_reg_next[74] = PreviousLag2_reg[73];
  assign PreviousLag2_reg_next[75] = PreviousLag2_reg[74];
  assign PreviousLag2_reg_next[76] = PreviousLag2_reg[75];
  assign PreviousLag2_reg_next[77] = PreviousLag2_reg[76];
  assign PreviousLag2_reg_next[78] = PreviousLag2_reg[77];
  assign PreviousLag2_reg_next[79] = PreviousLag2_reg[78];
  assign PreviousLag2_reg_next[80] = PreviousLag2_reg[79];
  assign PreviousLag2_reg_next[81] = PreviousLag2_reg[80];
  assign PreviousLag2_reg_next[82] = PreviousLag2_reg[81];
  assign PreviousLag2_reg_next[83] = PreviousLag2_reg[82];
  assign PreviousLag2_reg_next[84] = PreviousLag2_reg[83];
  assign PreviousLag2_reg_next[85] = PreviousLag2_reg[84];
  assign PreviousLag2_reg_next[86] = PreviousLag2_reg[85];
  assign PreviousLag2_reg_next[87] = PreviousLag2_reg[86];
  assign PreviousLag2_reg_next[88] = PreviousLag2_reg[87];
  assign PreviousLag2_reg_next[89] = PreviousLag2_reg[88];
  assign PreviousLag2_reg_next[90] = PreviousLag2_reg[89];
  assign PreviousLag2_reg_next[91] = PreviousLag2_reg[90];
  assign PreviousLag2_reg_next[92] = PreviousLag2_reg[91];
  assign PreviousLag2_reg_next[93] = PreviousLag2_reg[92];
  assign PreviousLag2_reg_next[94] = PreviousLag2_reg[93];
  assign PreviousLag2_reg_next[95] = PreviousLag2_reg[94];
  assign PreviousLag2_reg_next[96] = PreviousLag2_reg[95];
  assign PreviousLag2_reg_next[97] = PreviousLag2_reg[96];
  assign PreviousLag2_reg_next[98] = PreviousLag2_reg[97];
  assign PreviousLag2_reg_next[99] = PreviousLag2_reg[98];



  assign Add8_out1 = Delay14_out1 - PreviousLag2_out1;



  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= Add8_out1;
        end
      end
    end



  assign Add9_add_cast = {Delay3_out1[33], Delay3_out1};
  assign Add9_add_cast_1 = {Delay7_out1[33], Delay7_out1};
  assign Add9_add_temp = Add9_add_cast + Add9_add_cast_1;
  assign Add9_out1 = ((Add9_add_temp[34] == 1'b0) && (Add9_add_temp[33] != 1'b0) ? 34'sh1FFFFFFFF :
              ((Add9_add_temp[34] == 1'b1) && (Add9_add_temp[33] != 1'b1) ? 34'sh200000000 :
              $signed(Add9_add_temp[33:0])));



  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay7_out1 <= Add9_out1;
        end
      end
    end



  assign Compensatory_Lag_Sum = Delay7_out1;

endmodule  // Compensatory_Lag_Cells_HDL

