// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\SimulinkCFARHDLWorkflowExampleNew\Compensatory_Lead_Cells_HDL.v
// Created: 2023-05-30 17:04:46
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Compensatory_Lead_Cells_HDL
// Source Path: SimulinkCFARHDLWorkflowExampleNew/CFAR Implementation Model/CFAR Core/Training HDL/Compensatory Lead 
// Cells HD
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Compensatory_Lead_Cells_HDL
          (clk,
           reset,
           enb,
           CUTidx,
           SQR_LAW,
           Compensatory_Lead_Sum);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] CUTidx;  // int16
  input   signed [33:0] SQR_LAW;  // sfix34_En12
  output  signed [33:0] Compensatory_Lead_Sum;  // sfix34_En12


  reg signed [15:0] Delay4_reg [0:202];  // sfix16 [203]
  wire signed [15:0] Delay4_reg_next [0:202];  // sfix16 [203]
  wire signed [15:0] Delay4_out1;  // int16
  wire signed [15:0] ng_out1;  // int16
  reg signed [15:0] Delay1_out1;  // int16
  wire signed [15:0] CUTidx_Ng_out1;  // int16
  reg signed [15:0] Delay10_out1;  // int16
  wire switch_compare_1;
  reg signed [33:0] reduced_reg [0:1];  // sfix34 [2]
  wire signed [33:0] reduced_reg_next [0:1];  // sfix34_En12 [2]
  wire signed [33:0] SQR_LAW_1;  // sfix34_En12
  wire signed [33:0] alpha0_out1;  // sfix34_En12
  reg signed [33:0] Delay11_reg [0:1];  // sfix34 [2]
  wire signed [33:0] Delay11_reg_next [0:1];  // sfix34_En12 [2]
  wire signed [33:0] Delay11_out1;  // sfix34_En12
  wire signed [33:0] Compare_to_1_out1;  // sfix34_En12
  reg signed [33:0] Delay2_out1;  // sfix34_En12
  wire switch_compare_1_1;
  reg signed [33:0] reduced_reg_1 [0:99];  // sfix34 [100]
  wire signed [33:0] reduced_reg_next_1 [0:99];  // sfix34_En12 [100]
  wire signed [33:0] SQR_LAW_2;  // sfix34_En12
  wire signed [33:0] Compare_to_NT_1_out1;  // sfix34_En12
  reg signed [33:0] Delay3_out1;  // sfix34_En12
  wire signed [34:0] Add1_stage2_sub_cast;  // sfix35_En12
  wire signed [34:0] Add1_stage2_sub_cast_1;  // sfix35_En12
  wire signed [34:0] Add1_stage2_sub_temp;  // sfix35_En12
  wire signed [33:0] Add1_op_stage1;  // sfix34_En12
  reg signed [33:0] Delay7_out1;  // sfix34_En12
  wire signed [34:0] Add1_stage3_add_cast;  // sfix35_En12
  wire signed [34:0] Add1_stage3_add_cast_1;  // sfix35_En12
  wire signed [34:0] Add1_stage3_add_temp;  // sfix35_En12
  wire signed [33:0] Add1_out1;  // sfix34_En12
  reg signed [33:0] Delay14_reg [0:1];  // sfix34 [2]
  wire signed [33:0] Delay14_reg_next [0:1];  // sfix34_En12 [2]
  wire signed [33:0] Delay14_out1;  // sfix34_En12


  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_reg[0] <= 16'sb0000000000000000;
        Delay4_reg[1] <= 16'sb0000000000000000;
        Delay4_reg[2] <= 16'sb0000000000000000;
        Delay4_reg[3] <= 16'sb0000000000000000;
        Delay4_reg[4] <= 16'sb0000000000000000;
        Delay4_reg[5] <= 16'sb0000000000000000;
        Delay4_reg[6] <= 16'sb0000000000000000;
        Delay4_reg[7] <= 16'sb0000000000000000;
        Delay4_reg[8] <= 16'sb0000000000000000;
        Delay4_reg[9] <= 16'sb0000000000000000;
        Delay4_reg[10] <= 16'sb0000000000000000;
        Delay4_reg[11] <= 16'sb0000000000000000;
        Delay4_reg[12] <= 16'sb0000000000000000;
        Delay4_reg[13] <= 16'sb0000000000000000;
        Delay4_reg[14] <= 16'sb0000000000000000;
        Delay4_reg[15] <= 16'sb0000000000000000;
        Delay4_reg[16] <= 16'sb0000000000000000;
        Delay4_reg[17] <= 16'sb0000000000000000;
        Delay4_reg[18] <= 16'sb0000000000000000;
        Delay4_reg[19] <= 16'sb0000000000000000;
        Delay4_reg[20] <= 16'sb0000000000000000;
        Delay4_reg[21] <= 16'sb0000000000000000;
        Delay4_reg[22] <= 16'sb0000000000000000;
        Delay4_reg[23] <= 16'sb0000000000000000;
        Delay4_reg[24] <= 16'sb0000000000000000;
        Delay4_reg[25] <= 16'sb0000000000000000;
        Delay4_reg[26] <= 16'sb0000000000000000;
        Delay4_reg[27] <= 16'sb0000000000000000;
        Delay4_reg[28] <= 16'sb0000000000000000;
        Delay4_reg[29] <= 16'sb0000000000000000;
        Delay4_reg[30] <= 16'sb0000000000000000;
        Delay4_reg[31] <= 16'sb0000000000000000;
        Delay4_reg[32] <= 16'sb0000000000000000;
        Delay4_reg[33] <= 16'sb0000000000000000;
        Delay4_reg[34] <= 16'sb0000000000000000;
        Delay4_reg[35] <= 16'sb0000000000000000;
        Delay4_reg[36] <= 16'sb0000000000000000;
        Delay4_reg[37] <= 16'sb0000000000000000;
        Delay4_reg[38] <= 16'sb0000000000000000;
        Delay4_reg[39] <= 16'sb0000000000000000;
        Delay4_reg[40] <= 16'sb0000000000000000;
        Delay4_reg[41] <= 16'sb0000000000000000;
        Delay4_reg[42] <= 16'sb0000000000000000;
        Delay4_reg[43] <= 16'sb0000000000000000;
        Delay4_reg[44] <= 16'sb0000000000000000;
        Delay4_reg[45] <= 16'sb0000000000000000;
        Delay4_reg[46] <= 16'sb0000000000000000;
        Delay4_reg[47] <= 16'sb0000000000000000;
        Delay4_reg[48] <= 16'sb0000000000000000;
        Delay4_reg[49] <= 16'sb0000000000000000;
        Delay4_reg[50] <= 16'sb0000000000000000;
        Delay4_reg[51] <= 16'sb0000000000000000;
        Delay4_reg[52] <= 16'sb0000000000000000;
        Delay4_reg[53] <= 16'sb0000000000000000;
        Delay4_reg[54] <= 16'sb0000000000000000;
        Delay4_reg[55] <= 16'sb0000000000000000;
        Delay4_reg[56] <= 16'sb0000000000000000;
        Delay4_reg[57] <= 16'sb0000000000000000;
        Delay4_reg[58] <= 16'sb0000000000000000;
        Delay4_reg[59] <= 16'sb0000000000000000;
        Delay4_reg[60] <= 16'sb0000000000000000;
        Delay4_reg[61] <= 16'sb0000000000000000;
        Delay4_reg[62] <= 16'sb0000000000000000;
        Delay4_reg[63] <= 16'sb0000000000000000;
        Delay4_reg[64] <= 16'sb0000000000000000;
        Delay4_reg[65] <= 16'sb0000000000000000;
        Delay4_reg[66] <= 16'sb0000000000000000;
        Delay4_reg[67] <= 16'sb0000000000000000;
        Delay4_reg[68] <= 16'sb0000000000000000;
        Delay4_reg[69] <= 16'sb0000000000000000;
        Delay4_reg[70] <= 16'sb0000000000000000;
        Delay4_reg[71] <= 16'sb0000000000000000;
        Delay4_reg[72] <= 16'sb0000000000000000;
        Delay4_reg[73] <= 16'sb0000000000000000;
        Delay4_reg[74] <= 16'sb0000000000000000;
        Delay4_reg[75] <= 16'sb0000000000000000;
        Delay4_reg[76] <= 16'sb0000000000000000;
        Delay4_reg[77] <= 16'sb0000000000000000;
        Delay4_reg[78] <= 16'sb0000000000000000;
        Delay4_reg[79] <= 16'sb0000000000000000;
        Delay4_reg[80] <= 16'sb0000000000000000;
        Delay4_reg[81] <= 16'sb0000000000000000;
        Delay4_reg[82] <= 16'sb0000000000000000;
        Delay4_reg[83] <= 16'sb0000000000000000;
        Delay4_reg[84] <= 16'sb0000000000000000;
        Delay4_reg[85] <= 16'sb0000000000000000;
        Delay4_reg[86] <= 16'sb0000000000000000;
        Delay4_reg[87] <= 16'sb0000000000000000;
        Delay4_reg[88] <= 16'sb0000000000000000;
        Delay4_reg[89] <= 16'sb0000000000000000;
        Delay4_reg[90] <= 16'sb0000000000000000;
        Delay4_reg[91] <= 16'sb0000000000000000;
        Delay4_reg[92] <= 16'sb0000000000000000;
        Delay4_reg[93] <= 16'sb0000000000000000;
        Delay4_reg[94] <= 16'sb0000000000000000;
        Delay4_reg[95] <= 16'sb0000000000000000;
        Delay4_reg[96] <= 16'sb0000000000000000;
        Delay4_reg[97] <= 16'sb0000000000000000;
        Delay4_reg[98] <= 16'sb0000000000000000;
        Delay4_reg[99] <= 16'sb0000000000000000;
        Delay4_reg[100] <= 16'sb0000000000000000;
        Delay4_reg[101] <= 16'sb0000000000000000;
        Delay4_reg[102] <= 16'sb0000000000000000;
        Delay4_reg[103] <= 16'sb0000000000000000;
        Delay4_reg[104] <= 16'sb0000000000000000;
        Delay4_reg[105] <= 16'sb0000000000000000;
        Delay4_reg[106] <= 16'sb0000000000000000;
        Delay4_reg[107] <= 16'sb0000000000000000;
        Delay4_reg[108] <= 16'sb0000000000000000;
        Delay4_reg[109] <= 16'sb0000000000000000;
        Delay4_reg[110] <= 16'sb0000000000000000;
        Delay4_reg[111] <= 16'sb0000000000000000;
        Delay4_reg[112] <= 16'sb0000000000000000;
        Delay4_reg[113] <= 16'sb0000000000000000;
        Delay4_reg[114] <= 16'sb0000000000000000;
        Delay4_reg[115] <= 16'sb0000000000000000;
        Delay4_reg[116] <= 16'sb0000000000000000;
        Delay4_reg[117] <= 16'sb0000000000000000;
        Delay4_reg[118] <= 16'sb0000000000000000;
        Delay4_reg[119] <= 16'sb0000000000000000;
        Delay4_reg[120] <= 16'sb0000000000000000;
        Delay4_reg[121] <= 16'sb0000000000000000;
        Delay4_reg[122] <= 16'sb0000000000000000;
        Delay4_reg[123] <= 16'sb0000000000000000;
        Delay4_reg[124] <= 16'sb0000000000000000;
        Delay4_reg[125] <= 16'sb0000000000000000;
        Delay4_reg[126] <= 16'sb0000000000000000;
        Delay4_reg[127] <= 16'sb0000000000000000;
        Delay4_reg[128] <= 16'sb0000000000000000;
        Delay4_reg[129] <= 16'sb0000000000000000;
        Delay4_reg[130] <= 16'sb0000000000000000;
        Delay4_reg[131] <= 16'sb0000000000000000;
        Delay4_reg[132] <= 16'sb0000000000000000;
        Delay4_reg[133] <= 16'sb0000000000000000;
        Delay4_reg[134] <= 16'sb0000000000000000;
        Delay4_reg[135] <= 16'sb0000000000000000;
        Delay4_reg[136] <= 16'sb0000000000000000;
        Delay4_reg[137] <= 16'sb0000000000000000;
        Delay4_reg[138] <= 16'sb0000000000000000;
        Delay4_reg[139] <= 16'sb0000000000000000;
        Delay4_reg[140] <= 16'sb0000000000000000;
        Delay4_reg[141] <= 16'sb0000000000000000;
        Delay4_reg[142] <= 16'sb0000000000000000;
        Delay4_reg[143] <= 16'sb0000000000000000;
        Delay4_reg[144] <= 16'sb0000000000000000;
        Delay4_reg[145] <= 16'sb0000000000000000;
        Delay4_reg[146] <= 16'sb0000000000000000;
        Delay4_reg[147] <= 16'sb0000000000000000;
        Delay4_reg[148] <= 16'sb0000000000000000;
        Delay4_reg[149] <= 16'sb0000000000000000;
        Delay4_reg[150] <= 16'sb0000000000000000;
        Delay4_reg[151] <= 16'sb0000000000000000;
        Delay4_reg[152] <= 16'sb0000000000000000;
        Delay4_reg[153] <= 16'sb0000000000000000;
        Delay4_reg[154] <= 16'sb0000000000000000;
        Delay4_reg[155] <= 16'sb0000000000000000;
        Delay4_reg[156] <= 16'sb0000000000000000;
        Delay4_reg[157] <= 16'sb0000000000000000;
        Delay4_reg[158] <= 16'sb0000000000000000;
        Delay4_reg[159] <= 16'sb0000000000000000;
        Delay4_reg[160] <= 16'sb0000000000000000;
        Delay4_reg[161] <= 16'sb0000000000000000;
        Delay4_reg[162] <= 16'sb0000000000000000;
        Delay4_reg[163] <= 16'sb0000000000000000;
        Delay4_reg[164] <= 16'sb0000000000000000;
        Delay4_reg[165] <= 16'sb0000000000000000;
        Delay4_reg[166] <= 16'sb0000000000000000;
        Delay4_reg[167] <= 16'sb0000000000000000;
        Delay4_reg[168] <= 16'sb0000000000000000;
        Delay4_reg[169] <= 16'sb0000000000000000;
        Delay4_reg[170] <= 16'sb0000000000000000;
        Delay4_reg[171] <= 16'sb0000000000000000;
        Delay4_reg[172] <= 16'sb0000000000000000;
        Delay4_reg[173] <= 16'sb0000000000000000;
        Delay4_reg[174] <= 16'sb0000000000000000;
        Delay4_reg[175] <= 16'sb0000000000000000;
        Delay4_reg[176] <= 16'sb0000000000000000;
        Delay4_reg[177] <= 16'sb0000000000000000;
        Delay4_reg[178] <= 16'sb0000000000000000;
        Delay4_reg[179] <= 16'sb0000000000000000;
        Delay4_reg[180] <= 16'sb0000000000000000;
        Delay4_reg[181] <= 16'sb0000000000000000;
        Delay4_reg[182] <= 16'sb0000000000000000;
        Delay4_reg[183] <= 16'sb0000000000000000;
        Delay4_reg[184] <= 16'sb0000000000000000;
        Delay4_reg[185] <= 16'sb0000000000000000;
        Delay4_reg[186] <= 16'sb0000000000000000;
        Delay4_reg[187] <= 16'sb0000000000000000;
        Delay4_reg[188] <= 16'sb0000000000000000;
        Delay4_reg[189] <= 16'sb0000000000000000;
        Delay4_reg[190] <= 16'sb0000000000000000;
        Delay4_reg[191] <= 16'sb0000000000000000;
        Delay4_reg[192] <= 16'sb0000000000000000;
        Delay4_reg[193] <= 16'sb0000000000000000;
        Delay4_reg[194] <= 16'sb0000000000000000;
        Delay4_reg[195] <= 16'sb0000000000000000;
        Delay4_reg[196] <= 16'sb0000000000000000;
        Delay4_reg[197] <= 16'sb0000000000000000;
        Delay4_reg[198] <= 16'sb0000000000000000;
        Delay4_reg[199] <= 16'sb0000000000000000;
        Delay4_reg[200] <= 16'sb0000000000000000;
        Delay4_reg[201] <= 16'sb0000000000000000;
        Delay4_reg[202] <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay4_reg[0] <= Delay4_reg_next[0];
          Delay4_reg[1] <= Delay4_reg_next[1];
          Delay4_reg[2] <= Delay4_reg_next[2];
          Delay4_reg[3] <= Delay4_reg_next[3];
          Delay4_reg[4] <= Delay4_reg_next[4];
          Delay4_reg[5] <= Delay4_reg_next[5];
          Delay4_reg[6] <= Delay4_reg_next[6];
          Delay4_reg[7] <= Delay4_reg_next[7];
          Delay4_reg[8] <= Delay4_reg_next[8];
          Delay4_reg[9] <= Delay4_reg_next[9];
          Delay4_reg[10] <= Delay4_reg_next[10];
          Delay4_reg[11] <= Delay4_reg_next[11];
          Delay4_reg[12] <= Delay4_reg_next[12];
          Delay4_reg[13] <= Delay4_reg_next[13];
          Delay4_reg[14] <= Delay4_reg_next[14];
          Delay4_reg[15] <= Delay4_reg_next[15];
          Delay4_reg[16] <= Delay4_reg_next[16];
          Delay4_reg[17] <= Delay4_reg_next[17];
          Delay4_reg[18] <= Delay4_reg_next[18];
          Delay4_reg[19] <= Delay4_reg_next[19];
          Delay4_reg[20] <= Delay4_reg_next[20];
          Delay4_reg[21] <= Delay4_reg_next[21];
          Delay4_reg[22] <= Delay4_reg_next[22];
          Delay4_reg[23] <= Delay4_reg_next[23];
          Delay4_reg[24] <= Delay4_reg_next[24];
          Delay4_reg[25] <= Delay4_reg_next[25];
          Delay4_reg[26] <= Delay4_reg_next[26];
          Delay4_reg[27] <= Delay4_reg_next[27];
          Delay4_reg[28] <= Delay4_reg_next[28];
          Delay4_reg[29] <= Delay4_reg_next[29];
          Delay4_reg[30] <= Delay4_reg_next[30];
          Delay4_reg[31] <= Delay4_reg_next[31];
          Delay4_reg[32] <= Delay4_reg_next[32];
          Delay4_reg[33] <= Delay4_reg_next[33];
          Delay4_reg[34] <= Delay4_reg_next[34];
          Delay4_reg[35] <= Delay4_reg_next[35];
          Delay4_reg[36] <= Delay4_reg_next[36];
          Delay4_reg[37] <= Delay4_reg_next[37];
          Delay4_reg[38] <= Delay4_reg_next[38];
          Delay4_reg[39] <= Delay4_reg_next[39];
          Delay4_reg[40] <= Delay4_reg_next[40];
          Delay4_reg[41] <= Delay4_reg_next[41];
          Delay4_reg[42] <= Delay4_reg_next[42];
          Delay4_reg[43] <= Delay4_reg_next[43];
          Delay4_reg[44] <= Delay4_reg_next[44];
          Delay4_reg[45] <= Delay4_reg_next[45];
          Delay4_reg[46] <= Delay4_reg_next[46];
          Delay4_reg[47] <= Delay4_reg_next[47];
          Delay4_reg[48] <= Delay4_reg_next[48];
          Delay4_reg[49] <= Delay4_reg_next[49];
          Delay4_reg[50] <= Delay4_reg_next[50];
          Delay4_reg[51] <= Delay4_reg_next[51];
          Delay4_reg[52] <= Delay4_reg_next[52];
          Delay4_reg[53] <= Delay4_reg_next[53];
          Delay4_reg[54] <= Delay4_reg_next[54];
          Delay4_reg[55] <= Delay4_reg_next[55];
          Delay4_reg[56] <= Delay4_reg_next[56];
          Delay4_reg[57] <= Delay4_reg_next[57];
          Delay4_reg[58] <= Delay4_reg_next[58];
          Delay4_reg[59] <= Delay4_reg_next[59];
          Delay4_reg[60] <= Delay4_reg_next[60];
          Delay4_reg[61] <= Delay4_reg_next[61];
          Delay4_reg[62] <= Delay4_reg_next[62];
          Delay4_reg[63] <= Delay4_reg_next[63];
          Delay4_reg[64] <= Delay4_reg_next[64];
          Delay4_reg[65] <= Delay4_reg_next[65];
          Delay4_reg[66] <= Delay4_reg_next[66];
          Delay4_reg[67] <= Delay4_reg_next[67];
          Delay4_reg[68] <= Delay4_reg_next[68];
          Delay4_reg[69] <= Delay4_reg_next[69];
          Delay4_reg[70] <= Delay4_reg_next[70];
          Delay4_reg[71] <= Delay4_reg_next[71];
          Delay4_reg[72] <= Delay4_reg_next[72];
          Delay4_reg[73] <= Delay4_reg_next[73];
          Delay4_reg[74] <= Delay4_reg_next[74];
          Delay4_reg[75] <= Delay4_reg_next[75];
          Delay4_reg[76] <= Delay4_reg_next[76];
          Delay4_reg[77] <= Delay4_reg_next[77];
          Delay4_reg[78] <= Delay4_reg_next[78];
          Delay4_reg[79] <= Delay4_reg_next[79];
          Delay4_reg[80] <= Delay4_reg_next[80];
          Delay4_reg[81] <= Delay4_reg_next[81];
          Delay4_reg[82] <= Delay4_reg_next[82];
          Delay4_reg[83] <= Delay4_reg_next[83];
          Delay4_reg[84] <= Delay4_reg_next[84];
          Delay4_reg[85] <= Delay4_reg_next[85];
          Delay4_reg[86] <= Delay4_reg_next[86];
          Delay4_reg[87] <= Delay4_reg_next[87];
          Delay4_reg[88] <= Delay4_reg_next[88];
          Delay4_reg[89] <= Delay4_reg_next[89];
          Delay4_reg[90] <= Delay4_reg_next[90];
          Delay4_reg[91] <= Delay4_reg_next[91];
          Delay4_reg[92] <= Delay4_reg_next[92];
          Delay4_reg[93] <= Delay4_reg_next[93];
          Delay4_reg[94] <= Delay4_reg_next[94];
          Delay4_reg[95] <= Delay4_reg_next[95];
          Delay4_reg[96] <= Delay4_reg_next[96];
          Delay4_reg[97] <= Delay4_reg_next[97];
          Delay4_reg[98] <= Delay4_reg_next[98];
          Delay4_reg[99] <= Delay4_reg_next[99];
          Delay4_reg[100] <= Delay4_reg_next[100];
          Delay4_reg[101] <= Delay4_reg_next[101];
          Delay4_reg[102] <= Delay4_reg_next[102];
          Delay4_reg[103] <= Delay4_reg_next[103];
          Delay4_reg[104] <= Delay4_reg_next[104];
          Delay4_reg[105] <= Delay4_reg_next[105];
          Delay4_reg[106] <= Delay4_reg_next[106];
          Delay4_reg[107] <= Delay4_reg_next[107];
          Delay4_reg[108] <= Delay4_reg_next[108];
          Delay4_reg[109] <= Delay4_reg_next[109];
          Delay4_reg[110] <= Delay4_reg_next[110];
          Delay4_reg[111] <= Delay4_reg_next[111];
          Delay4_reg[112] <= Delay4_reg_next[112];
          Delay4_reg[113] <= Delay4_reg_next[113];
          Delay4_reg[114] <= Delay4_reg_next[114];
          Delay4_reg[115] <= Delay4_reg_next[115];
          Delay4_reg[116] <= Delay4_reg_next[116];
          Delay4_reg[117] <= Delay4_reg_next[117];
          Delay4_reg[118] <= Delay4_reg_next[118];
          Delay4_reg[119] <= Delay4_reg_next[119];
          Delay4_reg[120] <= Delay4_reg_next[120];
          Delay4_reg[121] <= Delay4_reg_next[121];
          Delay4_reg[122] <= Delay4_reg_next[122];
          Delay4_reg[123] <= Delay4_reg_next[123];
          Delay4_reg[124] <= Delay4_reg_next[124];
          Delay4_reg[125] <= Delay4_reg_next[125];
          Delay4_reg[126] <= Delay4_reg_next[126];
          Delay4_reg[127] <= Delay4_reg_next[127];
          Delay4_reg[128] <= Delay4_reg_next[128];
          Delay4_reg[129] <= Delay4_reg_next[129];
          Delay4_reg[130] <= Delay4_reg_next[130];
          Delay4_reg[131] <= Delay4_reg_next[131];
          Delay4_reg[132] <= Delay4_reg_next[132];
          Delay4_reg[133] <= Delay4_reg_next[133];
          Delay4_reg[134] <= Delay4_reg_next[134];
          Delay4_reg[135] <= Delay4_reg_next[135];
          Delay4_reg[136] <= Delay4_reg_next[136];
          Delay4_reg[137] <= Delay4_reg_next[137];
          Delay4_reg[138] <= Delay4_reg_next[138];
          Delay4_reg[139] <= Delay4_reg_next[139];
          Delay4_reg[140] <= Delay4_reg_next[140];
          Delay4_reg[141] <= Delay4_reg_next[141];
          Delay4_reg[142] <= Delay4_reg_next[142];
          Delay4_reg[143] <= Delay4_reg_next[143];
          Delay4_reg[144] <= Delay4_reg_next[144];
          Delay4_reg[145] <= Delay4_reg_next[145];
          Delay4_reg[146] <= Delay4_reg_next[146];
          Delay4_reg[147] <= Delay4_reg_next[147];
          Delay4_reg[148] <= Delay4_reg_next[148];
          Delay4_reg[149] <= Delay4_reg_next[149];
          Delay4_reg[150] <= Delay4_reg_next[150];
          Delay4_reg[151] <= Delay4_reg_next[151];
          Delay4_reg[152] <= Delay4_reg_next[152];
          Delay4_reg[153] <= Delay4_reg_next[153];
          Delay4_reg[154] <= Delay4_reg_next[154];
          Delay4_reg[155] <= Delay4_reg_next[155];
          Delay4_reg[156] <= Delay4_reg_next[156];
          Delay4_reg[157] <= Delay4_reg_next[157];
          Delay4_reg[158] <= Delay4_reg_next[158];
          Delay4_reg[159] <= Delay4_reg_next[159];
          Delay4_reg[160] <= Delay4_reg_next[160];
          Delay4_reg[161] <= Delay4_reg_next[161];
          Delay4_reg[162] <= Delay4_reg_next[162];
          Delay4_reg[163] <= Delay4_reg_next[163];
          Delay4_reg[164] <= Delay4_reg_next[164];
          Delay4_reg[165] <= Delay4_reg_next[165];
          Delay4_reg[166] <= Delay4_reg_next[166];
          Delay4_reg[167] <= Delay4_reg_next[167];
          Delay4_reg[168] <= Delay4_reg_next[168];
          Delay4_reg[169] <= Delay4_reg_next[169];
          Delay4_reg[170] <= Delay4_reg_next[170];
          Delay4_reg[171] <= Delay4_reg_next[171];
          Delay4_reg[172] <= Delay4_reg_next[172];
          Delay4_reg[173] <= Delay4_reg_next[173];
          Delay4_reg[174] <= Delay4_reg_next[174];
          Delay4_reg[175] <= Delay4_reg_next[175];
          Delay4_reg[176] <= Delay4_reg_next[176];
          Delay4_reg[177] <= Delay4_reg_next[177];
          Delay4_reg[178] <= Delay4_reg_next[178];
          Delay4_reg[179] <= Delay4_reg_next[179];
          Delay4_reg[180] <= Delay4_reg_next[180];
          Delay4_reg[181] <= Delay4_reg_next[181];
          Delay4_reg[182] <= Delay4_reg_next[182];
          Delay4_reg[183] <= Delay4_reg_next[183];
          Delay4_reg[184] <= Delay4_reg_next[184];
          Delay4_reg[185] <= Delay4_reg_next[185];
          Delay4_reg[186] <= Delay4_reg_next[186];
          Delay4_reg[187] <= Delay4_reg_next[187];
          Delay4_reg[188] <= Delay4_reg_next[188];
          Delay4_reg[189] <= Delay4_reg_next[189];
          Delay4_reg[190] <= Delay4_reg_next[190];
          Delay4_reg[191] <= Delay4_reg_next[191];
          Delay4_reg[192] <= Delay4_reg_next[192];
          Delay4_reg[193] <= Delay4_reg_next[193];
          Delay4_reg[194] <= Delay4_reg_next[194];
          Delay4_reg[195] <= Delay4_reg_next[195];
          Delay4_reg[196] <= Delay4_reg_next[196];
          Delay4_reg[197] <= Delay4_reg_next[197];
          Delay4_reg[198] <= Delay4_reg_next[198];
          Delay4_reg[199] <= Delay4_reg_next[199];
          Delay4_reg[200] <= Delay4_reg_next[200];
          Delay4_reg[201] <= Delay4_reg_next[201];
          Delay4_reg[202] <= Delay4_reg_next[202];
        end
      end
    end

  assign Delay4_out1 = Delay4_reg[202];
  assign Delay4_reg_next[0] = CUTidx;
  assign Delay4_reg_next[1] = Delay4_reg[0];
  assign Delay4_reg_next[2] = Delay4_reg[1];
  assign Delay4_reg_next[3] = Delay4_reg[2];
  assign Delay4_reg_next[4] = Delay4_reg[3];
  assign Delay4_reg_next[5] = Delay4_reg[4];
  assign Delay4_reg_next[6] = Delay4_reg[5];
  assign Delay4_reg_next[7] = Delay4_reg[6];
  assign Delay4_reg_next[8] = Delay4_reg[7];
  assign Delay4_reg_next[9] = Delay4_reg[8];
  assign Delay4_reg_next[10] = Delay4_reg[9];
  assign Delay4_reg_next[11] = Delay4_reg[10];
  assign Delay4_reg_next[12] = Delay4_reg[11];
  assign Delay4_reg_next[13] = Delay4_reg[12];
  assign Delay4_reg_next[14] = Delay4_reg[13];
  assign Delay4_reg_next[15] = Delay4_reg[14];
  assign Delay4_reg_next[16] = Delay4_reg[15];
  assign Delay4_reg_next[17] = Delay4_reg[16];
  assign Delay4_reg_next[18] = Delay4_reg[17];
  assign Delay4_reg_next[19] = Delay4_reg[18];
  assign Delay4_reg_next[20] = Delay4_reg[19];
  assign Delay4_reg_next[21] = Delay4_reg[20];
  assign Delay4_reg_next[22] = Delay4_reg[21];
  assign Delay4_reg_next[23] = Delay4_reg[22];
  assign Delay4_reg_next[24] = Delay4_reg[23];
  assign Delay4_reg_next[25] = Delay4_reg[24];
  assign Delay4_reg_next[26] = Delay4_reg[25];
  assign Delay4_reg_next[27] = Delay4_reg[26];
  assign Delay4_reg_next[28] = Delay4_reg[27];
  assign Delay4_reg_next[29] = Delay4_reg[28];
  assign Delay4_reg_next[30] = Delay4_reg[29];
  assign Delay4_reg_next[31] = Delay4_reg[30];
  assign Delay4_reg_next[32] = Delay4_reg[31];
  assign Delay4_reg_next[33] = Delay4_reg[32];
  assign Delay4_reg_next[34] = Delay4_reg[33];
  assign Delay4_reg_next[35] = Delay4_reg[34];
  assign Delay4_reg_next[36] = Delay4_reg[35];
  assign Delay4_reg_next[37] = Delay4_reg[36];
  assign Delay4_reg_next[38] = Delay4_reg[37];
  assign Delay4_reg_next[39] = Delay4_reg[38];
  assign Delay4_reg_next[40] = Delay4_reg[39];
  assign Delay4_reg_next[41] = Delay4_reg[40];
  assign Delay4_reg_next[42] = Delay4_reg[41];
  assign Delay4_reg_next[43] = Delay4_reg[42];
  assign Delay4_reg_next[44] = Delay4_reg[43];
  assign Delay4_reg_next[45] = Delay4_reg[44];
  assign Delay4_reg_next[46] = Delay4_reg[45];
  assign Delay4_reg_next[47] = Delay4_reg[46];
  assign Delay4_reg_next[48] = Delay4_reg[47];
  assign Delay4_reg_next[49] = Delay4_reg[48];
  assign Delay4_reg_next[50] = Delay4_reg[49];
  assign Delay4_reg_next[51] = Delay4_reg[50];
  assign Delay4_reg_next[52] = Delay4_reg[51];
  assign Delay4_reg_next[53] = Delay4_reg[52];
  assign Delay4_reg_next[54] = Delay4_reg[53];
  assign Delay4_reg_next[55] = Delay4_reg[54];
  assign Delay4_reg_next[56] = Delay4_reg[55];
  assign Delay4_reg_next[57] = Delay4_reg[56];
  assign Delay4_reg_next[58] = Delay4_reg[57];
  assign Delay4_reg_next[59] = Delay4_reg[58];
  assign Delay4_reg_next[60] = Delay4_reg[59];
  assign Delay4_reg_next[61] = Delay4_reg[60];
  assign Delay4_reg_next[62] = Delay4_reg[61];
  assign Delay4_reg_next[63] = Delay4_reg[62];
  assign Delay4_reg_next[64] = Delay4_reg[63];
  assign Delay4_reg_next[65] = Delay4_reg[64];
  assign Delay4_reg_next[66] = Delay4_reg[65];
  assign Delay4_reg_next[67] = Delay4_reg[66];
  assign Delay4_reg_next[68] = Delay4_reg[67];
  assign Delay4_reg_next[69] = Delay4_reg[68];
  assign Delay4_reg_next[70] = Delay4_reg[69];
  assign Delay4_reg_next[71] = Delay4_reg[70];
  assign Delay4_reg_next[72] = Delay4_reg[71];
  assign Delay4_reg_next[73] = Delay4_reg[72];
  assign Delay4_reg_next[74] = Delay4_reg[73];
  assign Delay4_reg_next[75] = Delay4_reg[74];
  assign Delay4_reg_next[76] = Delay4_reg[75];
  assign Delay4_reg_next[77] = Delay4_reg[76];
  assign Delay4_reg_next[78] = Delay4_reg[77];
  assign Delay4_reg_next[79] = Delay4_reg[78];
  assign Delay4_reg_next[80] = Delay4_reg[79];
  assign Delay4_reg_next[81] = Delay4_reg[80];
  assign Delay4_reg_next[82] = Delay4_reg[81];
  assign Delay4_reg_next[83] = Delay4_reg[82];
  assign Delay4_reg_next[84] = Delay4_reg[83];
  assign Delay4_reg_next[85] = Delay4_reg[84];
  assign Delay4_reg_next[86] = Delay4_reg[85];
  assign Delay4_reg_next[87] = Delay4_reg[86];
  assign Delay4_reg_next[88] = Delay4_reg[87];
  assign Delay4_reg_next[89] = Delay4_reg[88];
  assign Delay4_reg_next[90] = Delay4_reg[89];
  assign Delay4_reg_next[91] = Delay4_reg[90];
  assign Delay4_reg_next[92] = Delay4_reg[91];
  assign Delay4_reg_next[93] = Delay4_reg[92];
  assign Delay4_reg_next[94] = Delay4_reg[93];
  assign Delay4_reg_next[95] = Delay4_reg[94];
  assign Delay4_reg_next[96] = Delay4_reg[95];
  assign Delay4_reg_next[97] = Delay4_reg[96];
  assign Delay4_reg_next[98] = Delay4_reg[97];
  assign Delay4_reg_next[99] = Delay4_reg[98];
  assign Delay4_reg_next[100] = Delay4_reg[99];
  assign Delay4_reg_next[101] = Delay4_reg[100];
  assign Delay4_reg_next[102] = Delay4_reg[101];
  assign Delay4_reg_next[103] = Delay4_reg[102];
  assign Delay4_reg_next[104] = Delay4_reg[103];
  assign Delay4_reg_next[105] = Delay4_reg[104];
  assign Delay4_reg_next[106] = Delay4_reg[105];
  assign Delay4_reg_next[107] = Delay4_reg[106];
  assign Delay4_reg_next[108] = Delay4_reg[107];
  assign Delay4_reg_next[109] = Delay4_reg[108];
  assign Delay4_reg_next[110] = Delay4_reg[109];
  assign Delay4_reg_next[111] = Delay4_reg[110];
  assign Delay4_reg_next[112] = Delay4_reg[111];
  assign Delay4_reg_next[113] = Delay4_reg[112];
  assign Delay4_reg_next[114] = Delay4_reg[113];
  assign Delay4_reg_next[115] = Delay4_reg[114];
  assign Delay4_reg_next[116] = Delay4_reg[115];
  assign Delay4_reg_next[117] = Delay4_reg[116];
  assign Delay4_reg_next[118] = Delay4_reg[117];
  assign Delay4_reg_next[119] = Delay4_reg[118];
  assign Delay4_reg_next[120] = Delay4_reg[119];
  assign Delay4_reg_next[121] = Delay4_reg[120];
  assign Delay4_reg_next[122] = Delay4_reg[121];
  assign Delay4_reg_next[123] = Delay4_reg[122];
  assign Delay4_reg_next[124] = Delay4_reg[123];
  assign Delay4_reg_next[125] = Delay4_reg[124];
  assign Delay4_reg_next[126] = Delay4_reg[125];
  assign Delay4_reg_next[127] = Delay4_reg[126];
  assign Delay4_reg_next[128] = Delay4_reg[127];
  assign Delay4_reg_next[129] = Delay4_reg[128];
  assign Delay4_reg_next[130] = Delay4_reg[129];
  assign Delay4_reg_next[131] = Delay4_reg[130];
  assign Delay4_reg_next[132] = Delay4_reg[131];
  assign Delay4_reg_next[133] = Delay4_reg[132];
  assign Delay4_reg_next[134] = Delay4_reg[133];
  assign Delay4_reg_next[135] = Delay4_reg[134];
  assign Delay4_reg_next[136] = Delay4_reg[135];
  assign Delay4_reg_next[137] = Delay4_reg[136];
  assign Delay4_reg_next[138] = Delay4_reg[137];
  assign Delay4_reg_next[139] = Delay4_reg[138];
  assign Delay4_reg_next[140] = Delay4_reg[139];
  assign Delay4_reg_next[141] = Delay4_reg[140];
  assign Delay4_reg_next[142] = Delay4_reg[141];
  assign Delay4_reg_next[143] = Delay4_reg[142];
  assign Delay4_reg_next[144] = Delay4_reg[143];
  assign Delay4_reg_next[145] = Delay4_reg[144];
  assign Delay4_reg_next[146] = Delay4_reg[145];
  assign Delay4_reg_next[147] = Delay4_reg[146];
  assign Delay4_reg_next[148] = Delay4_reg[147];
  assign Delay4_reg_next[149] = Delay4_reg[148];
  assign Delay4_reg_next[150] = Delay4_reg[149];
  assign Delay4_reg_next[151] = Delay4_reg[150];
  assign Delay4_reg_next[152] = Delay4_reg[151];
  assign Delay4_reg_next[153] = Delay4_reg[152];
  assign Delay4_reg_next[154] = Delay4_reg[153];
  assign Delay4_reg_next[155] = Delay4_reg[154];
  assign Delay4_reg_next[156] = Delay4_reg[155];
  assign Delay4_reg_next[157] = Delay4_reg[156];
  assign Delay4_reg_next[158] = Delay4_reg[157];
  assign Delay4_reg_next[159] = Delay4_reg[158];
  assign Delay4_reg_next[160] = Delay4_reg[159];
  assign Delay4_reg_next[161] = Delay4_reg[160];
  assign Delay4_reg_next[162] = Delay4_reg[161];
  assign Delay4_reg_next[163] = Delay4_reg[162];
  assign Delay4_reg_next[164] = Delay4_reg[163];
  assign Delay4_reg_next[165] = Delay4_reg[164];
  assign Delay4_reg_next[166] = Delay4_reg[165];
  assign Delay4_reg_next[167] = Delay4_reg[166];
  assign Delay4_reg_next[168] = Delay4_reg[167];
  assign Delay4_reg_next[169] = Delay4_reg[168];
  assign Delay4_reg_next[170] = Delay4_reg[169];
  assign Delay4_reg_next[171] = Delay4_reg[170];
  assign Delay4_reg_next[172] = Delay4_reg[171];
  assign Delay4_reg_next[173] = Delay4_reg[172];
  assign Delay4_reg_next[174] = Delay4_reg[173];
  assign Delay4_reg_next[175] = Delay4_reg[174];
  assign Delay4_reg_next[176] = Delay4_reg[175];
  assign Delay4_reg_next[177] = Delay4_reg[176];
  assign Delay4_reg_next[178] = Delay4_reg[177];
  assign Delay4_reg_next[179] = Delay4_reg[178];
  assign Delay4_reg_next[180] = Delay4_reg[179];
  assign Delay4_reg_next[181] = Delay4_reg[180];
  assign Delay4_reg_next[182] = Delay4_reg[181];
  assign Delay4_reg_next[183] = Delay4_reg[182];
  assign Delay4_reg_next[184] = Delay4_reg[183];
  assign Delay4_reg_next[185] = Delay4_reg[184];
  assign Delay4_reg_next[186] = Delay4_reg[185];
  assign Delay4_reg_next[187] = Delay4_reg[186];
  assign Delay4_reg_next[188] = Delay4_reg[187];
  assign Delay4_reg_next[189] = Delay4_reg[188];
  assign Delay4_reg_next[190] = Delay4_reg[189];
  assign Delay4_reg_next[191] = Delay4_reg[190];
  assign Delay4_reg_next[192] = Delay4_reg[191];
  assign Delay4_reg_next[193] = Delay4_reg[192];
  assign Delay4_reg_next[194] = Delay4_reg[193];
  assign Delay4_reg_next[195] = Delay4_reg[194];
  assign Delay4_reg_next[196] = Delay4_reg[195];
  assign Delay4_reg_next[197] = Delay4_reg[196];
  assign Delay4_reg_next[198] = Delay4_reg[197];
  assign Delay4_reg_next[199] = Delay4_reg[198];
  assign Delay4_reg_next[200] = Delay4_reg[199];
  assign Delay4_reg_next[201] = Delay4_reg[200];
  assign Delay4_reg_next[202] = Delay4_reg[201];



  assign ng_out1 = 16'sb0000000000000010;



  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= ng_out1;
        end
      end
    end



  assign CUTidx_Ng_out1 = Delay4_out1 - Delay1_out1;



  always @(posedge clk or posedge reset)
    begin : Delay10_process
      if (reset == 1'b1) begin
        Delay10_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay10_out1 <= CUTidx_Ng_out1;
        end
      end
    end



  assign switch_compare_1 = Delay10_out1 > 16'sb0000000000000001;



  always @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        reduced_reg[0] <= 34'sh000000000;
        reduced_reg[1] <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          reduced_reg[0] <= reduced_reg_next[0];
          reduced_reg[1] <= reduced_reg_next[1];
        end
      end
    end

  assign SQR_LAW_1 = reduced_reg[1];
  assign reduced_reg_next[0] = SQR_LAW;
  assign reduced_reg_next[1] = reduced_reg[0];



  assign alpha0_out1 = 34'sh000000000;



  always @(posedge clk or posedge reset)
    begin : Delay11_process
      if (reset == 1'b1) begin
        Delay11_reg[0] <= 34'sh000000000;
        Delay11_reg[1] <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay11_reg[0] <= Delay11_reg_next[0];
          Delay11_reg[1] <= Delay11_reg_next[1];
        end
      end
    end

  assign Delay11_out1 = Delay11_reg[1];
  assign Delay11_reg_next[0] = alpha0_out1;
  assign Delay11_reg_next[1] = Delay11_reg[0];



  assign Compare_to_1_out1 = (switch_compare_1 == 1'b0 ? SQR_LAW_1 :
              Delay11_out1);



  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= Compare_to_1_out1;
        end
      end
    end



  assign switch_compare_1_1 = Delay10_out1 > 16'sb0000000001100101;



  always @(posedge clk or posedge reset)
    begin : reduced_1_process
      if (reset == 1'b1) begin
        reduced_reg_1[0] <= 34'sh000000000;
        reduced_reg_1[1] <= 34'sh000000000;
        reduced_reg_1[2] <= 34'sh000000000;
        reduced_reg_1[3] <= 34'sh000000000;
        reduced_reg_1[4] <= 34'sh000000000;
        reduced_reg_1[5] <= 34'sh000000000;
        reduced_reg_1[6] <= 34'sh000000000;
        reduced_reg_1[7] <= 34'sh000000000;
        reduced_reg_1[8] <= 34'sh000000000;
        reduced_reg_1[9] <= 34'sh000000000;
        reduced_reg_1[10] <= 34'sh000000000;
        reduced_reg_1[11] <= 34'sh000000000;
        reduced_reg_1[12] <= 34'sh000000000;
        reduced_reg_1[13] <= 34'sh000000000;
        reduced_reg_1[14] <= 34'sh000000000;
        reduced_reg_1[15] <= 34'sh000000000;
        reduced_reg_1[16] <= 34'sh000000000;
        reduced_reg_1[17] <= 34'sh000000000;
        reduced_reg_1[18] <= 34'sh000000000;
        reduced_reg_1[19] <= 34'sh000000000;
        reduced_reg_1[20] <= 34'sh000000000;
        reduced_reg_1[21] <= 34'sh000000000;
        reduced_reg_1[22] <= 34'sh000000000;
        reduced_reg_1[23] <= 34'sh000000000;
        reduced_reg_1[24] <= 34'sh000000000;
        reduced_reg_1[25] <= 34'sh000000000;
        reduced_reg_1[26] <= 34'sh000000000;
        reduced_reg_1[27] <= 34'sh000000000;
        reduced_reg_1[28] <= 34'sh000000000;
        reduced_reg_1[29] <= 34'sh000000000;
        reduced_reg_1[30] <= 34'sh000000000;
        reduced_reg_1[31] <= 34'sh000000000;
        reduced_reg_1[32] <= 34'sh000000000;
        reduced_reg_1[33] <= 34'sh000000000;
        reduced_reg_1[34] <= 34'sh000000000;
        reduced_reg_1[35] <= 34'sh000000000;
        reduced_reg_1[36] <= 34'sh000000000;
        reduced_reg_1[37] <= 34'sh000000000;
        reduced_reg_1[38] <= 34'sh000000000;
        reduced_reg_1[39] <= 34'sh000000000;
        reduced_reg_1[40] <= 34'sh000000000;
        reduced_reg_1[41] <= 34'sh000000000;
        reduced_reg_1[42] <= 34'sh000000000;
        reduced_reg_1[43] <= 34'sh000000000;
        reduced_reg_1[44] <= 34'sh000000000;
        reduced_reg_1[45] <= 34'sh000000000;
        reduced_reg_1[46] <= 34'sh000000000;
        reduced_reg_1[47] <= 34'sh000000000;
        reduced_reg_1[48] <= 34'sh000000000;
        reduced_reg_1[49] <= 34'sh000000000;
        reduced_reg_1[50] <= 34'sh000000000;
        reduced_reg_1[51] <= 34'sh000000000;
        reduced_reg_1[52] <= 34'sh000000000;
        reduced_reg_1[53] <= 34'sh000000000;
        reduced_reg_1[54] <= 34'sh000000000;
        reduced_reg_1[55] <= 34'sh000000000;
        reduced_reg_1[56] <= 34'sh000000000;
        reduced_reg_1[57] <= 34'sh000000000;
        reduced_reg_1[58] <= 34'sh000000000;
        reduced_reg_1[59] <= 34'sh000000000;
        reduced_reg_1[60] <= 34'sh000000000;
        reduced_reg_1[61] <= 34'sh000000000;
        reduced_reg_1[62] <= 34'sh000000000;
        reduced_reg_1[63] <= 34'sh000000000;
        reduced_reg_1[64] <= 34'sh000000000;
        reduced_reg_1[65] <= 34'sh000000000;
        reduced_reg_1[66] <= 34'sh000000000;
        reduced_reg_1[67] <= 34'sh000000000;
        reduced_reg_1[68] <= 34'sh000000000;
        reduced_reg_1[69] <= 34'sh000000000;
        reduced_reg_1[70] <= 34'sh000000000;
        reduced_reg_1[71] <= 34'sh000000000;
        reduced_reg_1[72] <= 34'sh000000000;
        reduced_reg_1[73] <= 34'sh000000000;
        reduced_reg_1[74] <= 34'sh000000000;
        reduced_reg_1[75] <= 34'sh000000000;
        reduced_reg_1[76] <= 34'sh000000000;
        reduced_reg_1[77] <= 34'sh000000000;
        reduced_reg_1[78] <= 34'sh000000000;
        reduced_reg_1[79] <= 34'sh000000000;
        reduced_reg_1[80] <= 34'sh000000000;
        reduced_reg_1[81] <= 34'sh000000000;
        reduced_reg_1[82] <= 34'sh000000000;
        reduced_reg_1[83] <= 34'sh000000000;
        reduced_reg_1[84] <= 34'sh000000000;
        reduced_reg_1[85] <= 34'sh000000000;
        reduced_reg_1[86] <= 34'sh000000000;
        reduced_reg_1[87] <= 34'sh000000000;
        reduced_reg_1[88] <= 34'sh000000000;
        reduced_reg_1[89] <= 34'sh000000000;
        reduced_reg_1[90] <= 34'sh000000000;
        reduced_reg_1[91] <= 34'sh000000000;
        reduced_reg_1[92] <= 34'sh000000000;
        reduced_reg_1[93] <= 34'sh000000000;
        reduced_reg_1[94] <= 34'sh000000000;
        reduced_reg_1[95] <= 34'sh000000000;
        reduced_reg_1[96] <= 34'sh000000000;
        reduced_reg_1[97] <= 34'sh000000000;
        reduced_reg_1[98] <= 34'sh000000000;
        reduced_reg_1[99] <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          reduced_reg_1[0] <= reduced_reg_next_1[0];
          reduced_reg_1[1] <= reduced_reg_next_1[1];
          reduced_reg_1[2] <= reduced_reg_next_1[2];
          reduced_reg_1[3] <= reduced_reg_next_1[3];
          reduced_reg_1[4] <= reduced_reg_next_1[4];
          reduced_reg_1[5] <= reduced_reg_next_1[5];
          reduced_reg_1[6] <= reduced_reg_next_1[6];
          reduced_reg_1[7] <= reduced_reg_next_1[7];
          reduced_reg_1[8] <= reduced_reg_next_1[8];
          reduced_reg_1[9] <= reduced_reg_next_1[9];
          reduced_reg_1[10] <= reduced_reg_next_1[10];
          reduced_reg_1[11] <= reduced_reg_next_1[11];
          reduced_reg_1[12] <= reduced_reg_next_1[12];
          reduced_reg_1[13] <= reduced_reg_next_1[13];
          reduced_reg_1[14] <= reduced_reg_next_1[14];
          reduced_reg_1[15] <= reduced_reg_next_1[15];
          reduced_reg_1[16] <= reduced_reg_next_1[16];
          reduced_reg_1[17] <= reduced_reg_next_1[17];
          reduced_reg_1[18] <= reduced_reg_next_1[18];
          reduced_reg_1[19] <= reduced_reg_next_1[19];
          reduced_reg_1[20] <= reduced_reg_next_1[20];
          reduced_reg_1[21] <= reduced_reg_next_1[21];
          reduced_reg_1[22] <= reduced_reg_next_1[22];
          reduced_reg_1[23] <= reduced_reg_next_1[23];
          reduced_reg_1[24] <= reduced_reg_next_1[24];
          reduced_reg_1[25] <= reduced_reg_next_1[25];
          reduced_reg_1[26] <= reduced_reg_next_1[26];
          reduced_reg_1[27] <= reduced_reg_next_1[27];
          reduced_reg_1[28] <= reduced_reg_next_1[28];
          reduced_reg_1[29] <= reduced_reg_next_1[29];
          reduced_reg_1[30] <= reduced_reg_next_1[30];
          reduced_reg_1[31] <= reduced_reg_next_1[31];
          reduced_reg_1[32] <= reduced_reg_next_1[32];
          reduced_reg_1[33] <= reduced_reg_next_1[33];
          reduced_reg_1[34] <= reduced_reg_next_1[34];
          reduced_reg_1[35] <= reduced_reg_next_1[35];
          reduced_reg_1[36] <= reduced_reg_next_1[36];
          reduced_reg_1[37] <= reduced_reg_next_1[37];
          reduced_reg_1[38] <= reduced_reg_next_1[38];
          reduced_reg_1[39] <= reduced_reg_next_1[39];
          reduced_reg_1[40] <= reduced_reg_next_1[40];
          reduced_reg_1[41] <= reduced_reg_next_1[41];
          reduced_reg_1[42] <= reduced_reg_next_1[42];
          reduced_reg_1[43] <= reduced_reg_next_1[43];
          reduced_reg_1[44] <= reduced_reg_next_1[44];
          reduced_reg_1[45] <= reduced_reg_next_1[45];
          reduced_reg_1[46] <= reduced_reg_next_1[46];
          reduced_reg_1[47] <= reduced_reg_next_1[47];
          reduced_reg_1[48] <= reduced_reg_next_1[48];
          reduced_reg_1[49] <= reduced_reg_next_1[49];
          reduced_reg_1[50] <= reduced_reg_next_1[50];
          reduced_reg_1[51] <= reduced_reg_next_1[51];
          reduced_reg_1[52] <= reduced_reg_next_1[52];
          reduced_reg_1[53] <= reduced_reg_next_1[53];
          reduced_reg_1[54] <= reduced_reg_next_1[54];
          reduced_reg_1[55] <= reduced_reg_next_1[55];
          reduced_reg_1[56] <= reduced_reg_next_1[56];
          reduced_reg_1[57] <= reduced_reg_next_1[57];
          reduced_reg_1[58] <= reduced_reg_next_1[58];
          reduced_reg_1[59] <= reduced_reg_next_1[59];
          reduced_reg_1[60] <= reduced_reg_next_1[60];
          reduced_reg_1[61] <= reduced_reg_next_1[61];
          reduced_reg_1[62] <= reduced_reg_next_1[62];
          reduced_reg_1[63] <= reduced_reg_next_1[63];
          reduced_reg_1[64] <= reduced_reg_next_1[64];
          reduced_reg_1[65] <= reduced_reg_next_1[65];
          reduced_reg_1[66] <= reduced_reg_next_1[66];
          reduced_reg_1[67] <= reduced_reg_next_1[67];
          reduced_reg_1[68] <= reduced_reg_next_1[68];
          reduced_reg_1[69] <= reduced_reg_next_1[69];
          reduced_reg_1[70] <= reduced_reg_next_1[70];
          reduced_reg_1[71] <= reduced_reg_next_1[71];
          reduced_reg_1[72] <= reduced_reg_next_1[72];
          reduced_reg_1[73] <= reduced_reg_next_1[73];
          reduced_reg_1[74] <= reduced_reg_next_1[74];
          reduced_reg_1[75] <= reduced_reg_next_1[75];
          reduced_reg_1[76] <= reduced_reg_next_1[76];
          reduced_reg_1[77] <= reduced_reg_next_1[77];
          reduced_reg_1[78] <= reduced_reg_next_1[78];
          reduced_reg_1[79] <= reduced_reg_next_1[79];
          reduced_reg_1[80] <= reduced_reg_next_1[80];
          reduced_reg_1[81] <= reduced_reg_next_1[81];
          reduced_reg_1[82] <= reduced_reg_next_1[82];
          reduced_reg_1[83] <= reduced_reg_next_1[83];
          reduced_reg_1[84] <= reduced_reg_next_1[84];
          reduced_reg_1[85] <= reduced_reg_next_1[85];
          reduced_reg_1[86] <= reduced_reg_next_1[86];
          reduced_reg_1[87] <= reduced_reg_next_1[87];
          reduced_reg_1[88] <= reduced_reg_next_1[88];
          reduced_reg_1[89] <= reduced_reg_next_1[89];
          reduced_reg_1[90] <= reduced_reg_next_1[90];
          reduced_reg_1[91] <= reduced_reg_next_1[91];
          reduced_reg_1[92] <= reduced_reg_next_1[92];
          reduced_reg_1[93] <= reduced_reg_next_1[93];
          reduced_reg_1[94] <= reduced_reg_next_1[94];
          reduced_reg_1[95] <= reduced_reg_next_1[95];
          reduced_reg_1[96] <= reduced_reg_next_1[96];
          reduced_reg_1[97] <= reduced_reg_next_1[97];
          reduced_reg_1[98] <= reduced_reg_next_1[98];
          reduced_reg_1[99] <= reduced_reg_next_1[99];
        end
      end
    end

  assign SQR_LAW_2 = reduced_reg_1[99];
  assign reduced_reg_next_1[0] = SQR_LAW_1;
  assign reduced_reg_next_1[1] = reduced_reg_1[0];
  assign reduced_reg_next_1[2] = reduced_reg_1[1];
  assign reduced_reg_next_1[3] = reduced_reg_1[2];
  assign reduced_reg_next_1[4] = reduced_reg_1[3];
  assign reduced_reg_next_1[5] = reduced_reg_1[4];
  assign reduced_reg_next_1[6] = reduced_reg_1[5];
  assign reduced_reg_next_1[7] = reduced_reg_1[6];
  assign reduced_reg_next_1[8] = reduced_reg_1[7];
  assign reduced_reg_next_1[9] = reduced_reg_1[8];
  assign reduced_reg_next_1[10] = reduced_reg_1[9];
  assign reduced_reg_next_1[11] = reduced_reg_1[10];
  assign reduced_reg_next_1[12] = reduced_reg_1[11];
  assign reduced_reg_next_1[13] = reduced_reg_1[12];
  assign reduced_reg_next_1[14] = reduced_reg_1[13];
  assign reduced_reg_next_1[15] = reduced_reg_1[14];
  assign reduced_reg_next_1[16] = reduced_reg_1[15];
  assign reduced_reg_next_1[17] = reduced_reg_1[16];
  assign reduced_reg_next_1[18] = reduced_reg_1[17];
  assign reduced_reg_next_1[19] = reduced_reg_1[18];
  assign reduced_reg_next_1[20] = reduced_reg_1[19];
  assign reduced_reg_next_1[21] = reduced_reg_1[20];
  assign reduced_reg_next_1[22] = reduced_reg_1[21];
  assign reduced_reg_next_1[23] = reduced_reg_1[22];
  assign reduced_reg_next_1[24] = reduced_reg_1[23];
  assign reduced_reg_next_1[25] = reduced_reg_1[24];
  assign reduced_reg_next_1[26] = reduced_reg_1[25];
  assign reduced_reg_next_1[27] = reduced_reg_1[26];
  assign reduced_reg_next_1[28] = reduced_reg_1[27];
  assign reduced_reg_next_1[29] = reduced_reg_1[28];
  assign reduced_reg_next_1[30] = reduced_reg_1[29];
  assign reduced_reg_next_1[31] = reduced_reg_1[30];
  assign reduced_reg_next_1[32] = reduced_reg_1[31];
  assign reduced_reg_next_1[33] = reduced_reg_1[32];
  assign reduced_reg_next_1[34] = reduced_reg_1[33];
  assign reduced_reg_next_1[35] = reduced_reg_1[34];
  assign reduced_reg_next_1[36] = reduced_reg_1[35];
  assign reduced_reg_next_1[37] = reduced_reg_1[36];
  assign reduced_reg_next_1[38] = reduced_reg_1[37];
  assign reduced_reg_next_1[39] = reduced_reg_1[38];
  assign reduced_reg_next_1[40] = reduced_reg_1[39];
  assign reduced_reg_next_1[41] = reduced_reg_1[40];
  assign reduced_reg_next_1[42] = reduced_reg_1[41];
  assign reduced_reg_next_1[43] = reduced_reg_1[42];
  assign reduced_reg_next_1[44] = reduced_reg_1[43];
  assign reduced_reg_next_1[45] = reduced_reg_1[44];
  assign reduced_reg_next_1[46] = reduced_reg_1[45];
  assign reduced_reg_next_1[47] = reduced_reg_1[46];
  assign reduced_reg_next_1[48] = reduced_reg_1[47];
  assign reduced_reg_next_1[49] = reduced_reg_1[48];
  assign reduced_reg_next_1[50] = reduced_reg_1[49];
  assign reduced_reg_next_1[51] = reduced_reg_1[50];
  assign reduced_reg_next_1[52] = reduced_reg_1[51];
  assign reduced_reg_next_1[53] = reduced_reg_1[52];
  assign reduced_reg_next_1[54] = reduced_reg_1[53];
  assign reduced_reg_next_1[55] = reduced_reg_1[54];
  assign reduced_reg_next_1[56] = reduced_reg_1[55];
  assign reduced_reg_next_1[57] = reduced_reg_1[56];
  assign reduced_reg_next_1[58] = reduced_reg_1[57];
  assign reduced_reg_next_1[59] = reduced_reg_1[58];
  assign reduced_reg_next_1[60] = reduced_reg_1[59];
  assign reduced_reg_next_1[61] = reduced_reg_1[60];
  assign reduced_reg_next_1[62] = reduced_reg_1[61];
  assign reduced_reg_next_1[63] = reduced_reg_1[62];
  assign reduced_reg_next_1[64] = reduced_reg_1[63];
  assign reduced_reg_next_1[65] = reduced_reg_1[64];
  assign reduced_reg_next_1[66] = reduced_reg_1[65];
  assign reduced_reg_next_1[67] = reduced_reg_1[66];
  assign reduced_reg_next_1[68] = reduced_reg_1[67];
  assign reduced_reg_next_1[69] = reduced_reg_1[68];
  assign reduced_reg_next_1[70] = reduced_reg_1[69];
  assign reduced_reg_next_1[71] = reduced_reg_1[70];
  assign reduced_reg_next_1[72] = reduced_reg_1[71];
  assign reduced_reg_next_1[73] = reduced_reg_1[72];
  assign reduced_reg_next_1[74] = reduced_reg_1[73];
  assign reduced_reg_next_1[75] = reduced_reg_1[74];
  assign reduced_reg_next_1[76] = reduced_reg_1[75];
  assign reduced_reg_next_1[77] = reduced_reg_1[76];
  assign reduced_reg_next_1[78] = reduced_reg_1[77];
  assign reduced_reg_next_1[79] = reduced_reg_1[78];
  assign reduced_reg_next_1[80] = reduced_reg_1[79];
  assign reduced_reg_next_1[81] = reduced_reg_1[80];
  assign reduced_reg_next_1[82] = reduced_reg_1[81];
  assign reduced_reg_next_1[83] = reduced_reg_1[82];
  assign reduced_reg_next_1[84] = reduced_reg_1[83];
  assign reduced_reg_next_1[85] = reduced_reg_1[84];
  assign reduced_reg_next_1[86] = reduced_reg_1[85];
  assign reduced_reg_next_1[87] = reduced_reg_1[86];
  assign reduced_reg_next_1[88] = reduced_reg_1[87];
  assign reduced_reg_next_1[89] = reduced_reg_1[88];
  assign reduced_reg_next_1[90] = reduced_reg_1[89];
  assign reduced_reg_next_1[91] = reduced_reg_1[90];
  assign reduced_reg_next_1[92] = reduced_reg_1[91];
  assign reduced_reg_next_1[93] = reduced_reg_1[92];
  assign reduced_reg_next_1[94] = reduced_reg_1[93];
  assign reduced_reg_next_1[95] = reduced_reg_1[94];
  assign reduced_reg_next_1[96] = reduced_reg_1[95];
  assign reduced_reg_next_1[97] = reduced_reg_1[96];
  assign reduced_reg_next_1[98] = reduced_reg_1[97];
  assign reduced_reg_next_1[99] = reduced_reg_1[98];



  assign Compare_to_NT_1_out1 = (switch_compare_1_1 == 1'b0 ? SQR_LAW_2 :
              Delay11_out1);



  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= Compare_to_NT_1_out1;
        end
      end
    end



  assign Add1_stage2_sub_cast = {Delay2_out1[33], Delay2_out1};
  assign Add1_stage2_sub_cast_1 = {Delay3_out1[33], Delay3_out1};
  assign Add1_stage2_sub_temp = Add1_stage2_sub_cast - Add1_stage2_sub_cast_1;
  assign Add1_op_stage1 = ((Add1_stage2_sub_temp[34] == 1'b0) && (Add1_stage2_sub_temp[33] != 1'b0) ? 34'sh1FFFFFFFF :
              ((Add1_stage2_sub_temp[34] == 1'b1) && (Add1_stage2_sub_temp[33] != 1'b1) ? 34'sh200000000 :
              $signed(Add1_stage2_sub_temp[33:0])));



  assign Add1_stage3_add_cast = {Add1_op_stage1[33], Add1_op_stage1};
  assign Add1_stage3_add_cast_1 = {Delay7_out1[33], Delay7_out1};
  assign Add1_stage3_add_temp = Add1_stage3_add_cast + Add1_stage3_add_cast_1;
  assign Add1_out1 = ((Add1_stage3_add_temp[34] == 1'b0) && (Add1_stage3_add_temp[33] != 1'b0) ? 34'sh1FFFFFFFF :
              ((Add1_stage3_add_temp[34] == 1'b1) && (Add1_stage3_add_temp[33] != 1'b1) ? 34'sh200000000 :
              $signed(Add1_stage3_add_temp[33:0])));



  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay7_out1 <= Add1_out1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : Delay14_process
      if (reset == 1'b1) begin
        Delay14_reg[0] <= 34'sh000000000;
        Delay14_reg[1] <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay14_reg[0] <= Delay14_reg_next[0];
          Delay14_reg[1] <= Delay14_reg_next[1];
        end
      end
    end

  assign Delay14_out1 = Delay14_reg[1];
  assign Delay14_reg_next[0] = Delay7_out1;
  assign Delay14_reg_next[1] = Delay14_reg[0];



  assign Compensatory_Lead_Sum = Delay14_out1;

endmodule  // Compensatory_Lead_Cells_HDL

