// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\SimulinkCFARHDLWorkflowExampleNew\Lead_Cells_HDL.v
// Created: 2023-05-30 17:04:46
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Lead_Cells_HDL
// Source Path: SimulinkCFARHDLWorkflowExampleNew/CFAR Implementation Model/CFAR Core/Training HDL/Lead Cells HDL
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Lead_Cells_HDL
          (clk,
           reset,
           enb,
           SQR_LAW,
           Lead_Sum);


  input   clk;
  input   reset;
  input   enb;
  input   signed [33:0] SQR_LAW;  // sfix34_En12
  output  signed [33:0] Lead_Sum;  // sfix34_En12


  reg signed [33:0] Delay1_reg [0:100];  // sfix34 [101]
  wire signed [33:0] Delay1_reg_next [0:100];  // sfix34_En12 [101]
  wire signed [33:0] Delay1_out1;  // sfix34_En12
  reg signed [33:0] Subtract_Previous_reg [0:99];  // sfix34 [100]
  wire signed [33:0] Subtract_Previous_reg_next [0:99];  // sfix34_En12 [100]
  wire signed [33:0] Subtract_Previous_out1;  // sfix34_En12
  wire signed [33:0] Add2_out1;  // sfix34_En12
  reg signed [33:0] Delay3_out1;  // sfix34_En12
  reg signed [33:0] Delay7_out1;  // sfix34_En12
  wire signed [34:0] Add3_add_cast;  // sfix35_En12
  wire signed [34:0] Add3_add_cast_1;  // sfix35_En12
  wire signed [34:0] Add3_add_temp;  // sfix35_En12
  wire signed [33:0] Add3_out1;  // sfix34_En12
  reg signed [33:0] Delay2_reg [0:2];  // sfix34 [3]
  wire signed [33:0] Delay2_reg_next [0:2];  // sfix34_En12 [3]
  wire signed [33:0] Delay2_out1;  // sfix34_En12


  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_reg[0] <= 34'sh000000000;
        Delay1_reg[1] <= 34'sh000000000;
        Delay1_reg[2] <= 34'sh000000000;
        Delay1_reg[3] <= 34'sh000000000;
        Delay1_reg[4] <= 34'sh000000000;
        Delay1_reg[5] <= 34'sh000000000;
        Delay1_reg[6] <= 34'sh000000000;
        Delay1_reg[7] <= 34'sh000000000;
        Delay1_reg[8] <= 34'sh000000000;
        Delay1_reg[9] <= 34'sh000000000;
        Delay1_reg[10] <= 34'sh000000000;
        Delay1_reg[11] <= 34'sh000000000;
        Delay1_reg[12] <= 34'sh000000000;
        Delay1_reg[13] <= 34'sh000000000;
        Delay1_reg[14] <= 34'sh000000000;
        Delay1_reg[15] <= 34'sh000000000;
        Delay1_reg[16] <= 34'sh000000000;
        Delay1_reg[17] <= 34'sh000000000;
        Delay1_reg[18] <= 34'sh000000000;
        Delay1_reg[19] <= 34'sh000000000;
        Delay1_reg[20] <= 34'sh000000000;
        Delay1_reg[21] <= 34'sh000000000;
        Delay1_reg[22] <= 34'sh000000000;
        Delay1_reg[23] <= 34'sh000000000;
        Delay1_reg[24] <= 34'sh000000000;
        Delay1_reg[25] <= 34'sh000000000;
        Delay1_reg[26] <= 34'sh000000000;
        Delay1_reg[27] <= 34'sh000000000;
        Delay1_reg[28] <= 34'sh000000000;
        Delay1_reg[29] <= 34'sh000000000;
        Delay1_reg[30] <= 34'sh000000000;
        Delay1_reg[31] <= 34'sh000000000;
        Delay1_reg[32] <= 34'sh000000000;
        Delay1_reg[33] <= 34'sh000000000;
        Delay1_reg[34] <= 34'sh000000000;
        Delay1_reg[35] <= 34'sh000000000;
        Delay1_reg[36] <= 34'sh000000000;
        Delay1_reg[37] <= 34'sh000000000;
        Delay1_reg[38] <= 34'sh000000000;
        Delay1_reg[39] <= 34'sh000000000;
        Delay1_reg[40] <= 34'sh000000000;
        Delay1_reg[41] <= 34'sh000000000;
        Delay1_reg[42] <= 34'sh000000000;
        Delay1_reg[43] <= 34'sh000000000;
        Delay1_reg[44] <= 34'sh000000000;
        Delay1_reg[45] <= 34'sh000000000;
        Delay1_reg[46] <= 34'sh000000000;
        Delay1_reg[47] <= 34'sh000000000;
        Delay1_reg[48] <= 34'sh000000000;
        Delay1_reg[49] <= 34'sh000000000;
        Delay1_reg[50] <= 34'sh000000000;
        Delay1_reg[51] <= 34'sh000000000;
        Delay1_reg[52] <= 34'sh000000000;
        Delay1_reg[53] <= 34'sh000000000;
        Delay1_reg[54] <= 34'sh000000000;
        Delay1_reg[55] <= 34'sh000000000;
        Delay1_reg[56] <= 34'sh000000000;
        Delay1_reg[57] <= 34'sh000000000;
        Delay1_reg[58] <= 34'sh000000000;
        Delay1_reg[59] <= 34'sh000000000;
        Delay1_reg[60] <= 34'sh000000000;
        Delay1_reg[61] <= 34'sh000000000;
        Delay1_reg[62] <= 34'sh000000000;
        Delay1_reg[63] <= 34'sh000000000;
        Delay1_reg[64] <= 34'sh000000000;
        Delay1_reg[65] <= 34'sh000000000;
        Delay1_reg[66] <= 34'sh000000000;
        Delay1_reg[67] <= 34'sh000000000;
        Delay1_reg[68] <= 34'sh000000000;
        Delay1_reg[69] <= 34'sh000000000;
        Delay1_reg[70] <= 34'sh000000000;
        Delay1_reg[71] <= 34'sh000000000;
        Delay1_reg[72] <= 34'sh000000000;
        Delay1_reg[73] <= 34'sh000000000;
        Delay1_reg[74] <= 34'sh000000000;
        Delay1_reg[75] <= 34'sh000000000;
        Delay1_reg[76] <= 34'sh000000000;
        Delay1_reg[77] <= 34'sh000000000;
        Delay1_reg[78] <= 34'sh000000000;
        Delay1_reg[79] <= 34'sh000000000;
        Delay1_reg[80] <= 34'sh000000000;
        Delay1_reg[81] <= 34'sh000000000;
        Delay1_reg[82] <= 34'sh000000000;
        Delay1_reg[83] <= 34'sh000000000;
        Delay1_reg[84] <= 34'sh000000000;
        Delay1_reg[85] <= 34'sh000000000;
        Delay1_reg[86] <= 34'sh000000000;
        Delay1_reg[87] <= 34'sh000000000;
        Delay1_reg[88] <= 34'sh000000000;
        Delay1_reg[89] <= 34'sh000000000;
        Delay1_reg[90] <= 34'sh000000000;
        Delay1_reg[91] <= 34'sh000000000;
        Delay1_reg[92] <= 34'sh000000000;
        Delay1_reg[93] <= 34'sh000000000;
        Delay1_reg[94] <= 34'sh000000000;
        Delay1_reg[95] <= 34'sh000000000;
        Delay1_reg[96] <= 34'sh000000000;
        Delay1_reg[97] <= 34'sh000000000;
        Delay1_reg[98] <= 34'sh000000000;
        Delay1_reg[99] <= 34'sh000000000;
        Delay1_reg[100] <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_reg[0] <= Delay1_reg_next[0];
          Delay1_reg[1] <= Delay1_reg_next[1];
          Delay1_reg[2] <= Delay1_reg_next[2];
          Delay1_reg[3] <= Delay1_reg_next[3];
          Delay1_reg[4] <= Delay1_reg_next[4];
          Delay1_reg[5] <= Delay1_reg_next[5];
          Delay1_reg[6] <= Delay1_reg_next[6];
          Delay1_reg[7] <= Delay1_reg_next[7];
          Delay1_reg[8] <= Delay1_reg_next[8];
          Delay1_reg[9] <= Delay1_reg_next[9];
          Delay1_reg[10] <= Delay1_reg_next[10];
          Delay1_reg[11] <= Delay1_reg_next[11];
          Delay1_reg[12] <= Delay1_reg_next[12];
          Delay1_reg[13] <= Delay1_reg_next[13];
          Delay1_reg[14] <= Delay1_reg_next[14];
          Delay1_reg[15] <= Delay1_reg_next[15];
          Delay1_reg[16] <= Delay1_reg_next[16];
          Delay1_reg[17] <= Delay1_reg_next[17];
          Delay1_reg[18] <= Delay1_reg_next[18];
          Delay1_reg[19] <= Delay1_reg_next[19];
          Delay1_reg[20] <= Delay1_reg_next[20];
          Delay1_reg[21] <= Delay1_reg_next[21];
          Delay1_reg[22] <= Delay1_reg_next[22];
          Delay1_reg[23] <= Delay1_reg_next[23];
          Delay1_reg[24] <= Delay1_reg_next[24];
          Delay1_reg[25] <= Delay1_reg_next[25];
          Delay1_reg[26] <= Delay1_reg_next[26];
          Delay1_reg[27] <= Delay1_reg_next[27];
          Delay1_reg[28] <= Delay1_reg_next[28];
          Delay1_reg[29] <= Delay1_reg_next[29];
          Delay1_reg[30] <= Delay1_reg_next[30];
          Delay1_reg[31] <= Delay1_reg_next[31];
          Delay1_reg[32] <= Delay1_reg_next[32];
          Delay1_reg[33] <= Delay1_reg_next[33];
          Delay1_reg[34] <= Delay1_reg_next[34];
          Delay1_reg[35] <= Delay1_reg_next[35];
          Delay1_reg[36] <= Delay1_reg_next[36];
          Delay1_reg[37] <= Delay1_reg_next[37];
          Delay1_reg[38] <= Delay1_reg_next[38];
          Delay1_reg[39] <= Delay1_reg_next[39];
          Delay1_reg[40] <= Delay1_reg_next[40];
          Delay1_reg[41] <= Delay1_reg_next[41];
          Delay1_reg[42] <= Delay1_reg_next[42];
          Delay1_reg[43] <= Delay1_reg_next[43];
          Delay1_reg[44] <= Delay1_reg_next[44];
          Delay1_reg[45] <= Delay1_reg_next[45];
          Delay1_reg[46] <= Delay1_reg_next[46];
          Delay1_reg[47] <= Delay1_reg_next[47];
          Delay1_reg[48] <= Delay1_reg_next[48];
          Delay1_reg[49] <= Delay1_reg_next[49];
          Delay1_reg[50] <= Delay1_reg_next[50];
          Delay1_reg[51] <= Delay1_reg_next[51];
          Delay1_reg[52] <= Delay1_reg_next[52];
          Delay1_reg[53] <= Delay1_reg_next[53];
          Delay1_reg[54] <= Delay1_reg_next[54];
          Delay1_reg[55] <= Delay1_reg_next[55];
          Delay1_reg[56] <= Delay1_reg_next[56];
          Delay1_reg[57] <= Delay1_reg_next[57];
          Delay1_reg[58] <= Delay1_reg_next[58];
          Delay1_reg[59] <= Delay1_reg_next[59];
          Delay1_reg[60] <= Delay1_reg_next[60];
          Delay1_reg[61] <= Delay1_reg_next[61];
          Delay1_reg[62] <= Delay1_reg_next[62];
          Delay1_reg[63] <= Delay1_reg_next[63];
          Delay1_reg[64] <= Delay1_reg_next[64];
          Delay1_reg[65] <= Delay1_reg_next[65];
          Delay1_reg[66] <= Delay1_reg_next[66];
          Delay1_reg[67] <= Delay1_reg_next[67];
          Delay1_reg[68] <= Delay1_reg_next[68];
          Delay1_reg[69] <= Delay1_reg_next[69];
          Delay1_reg[70] <= Delay1_reg_next[70];
          Delay1_reg[71] <= Delay1_reg_next[71];
          Delay1_reg[72] <= Delay1_reg_next[72];
          Delay1_reg[73] <= Delay1_reg_next[73];
          Delay1_reg[74] <= Delay1_reg_next[74];
          Delay1_reg[75] <= Delay1_reg_next[75];
          Delay1_reg[76] <= Delay1_reg_next[76];
          Delay1_reg[77] <= Delay1_reg_next[77];
          Delay1_reg[78] <= Delay1_reg_next[78];
          Delay1_reg[79] <= Delay1_reg_next[79];
          Delay1_reg[80] <= Delay1_reg_next[80];
          Delay1_reg[81] <= Delay1_reg_next[81];
          Delay1_reg[82] <= Delay1_reg_next[82];
          Delay1_reg[83] <= Delay1_reg_next[83];
          Delay1_reg[84] <= Delay1_reg_next[84];
          Delay1_reg[85] <= Delay1_reg_next[85];
          Delay1_reg[86] <= Delay1_reg_next[86];
          Delay1_reg[87] <= Delay1_reg_next[87];
          Delay1_reg[88] <= Delay1_reg_next[88];
          Delay1_reg[89] <= Delay1_reg_next[89];
          Delay1_reg[90] <= Delay1_reg_next[90];
          Delay1_reg[91] <= Delay1_reg_next[91];
          Delay1_reg[92] <= Delay1_reg_next[92];
          Delay1_reg[93] <= Delay1_reg_next[93];
          Delay1_reg[94] <= Delay1_reg_next[94];
          Delay1_reg[95] <= Delay1_reg_next[95];
          Delay1_reg[96] <= Delay1_reg_next[96];
          Delay1_reg[97] <= Delay1_reg_next[97];
          Delay1_reg[98] <= Delay1_reg_next[98];
          Delay1_reg[99] <= Delay1_reg_next[99];
          Delay1_reg[100] <= Delay1_reg_next[100];
        end
      end
    end

  assign Delay1_out1 = Delay1_reg[100];
  assign Delay1_reg_next[0] = SQR_LAW;
  assign Delay1_reg_next[1] = Delay1_reg[0];
  assign Delay1_reg_next[2] = Delay1_reg[1];
  assign Delay1_reg_next[3] = Delay1_reg[2];
  assign Delay1_reg_next[4] = Delay1_reg[3];
  assign Delay1_reg_next[5] = Delay1_reg[4];
  assign Delay1_reg_next[6] = Delay1_reg[5];
  assign Delay1_reg_next[7] = Delay1_reg[6];
  assign Delay1_reg_next[8] = Delay1_reg[7];
  assign Delay1_reg_next[9] = Delay1_reg[8];
  assign Delay1_reg_next[10] = Delay1_reg[9];
  assign Delay1_reg_next[11] = Delay1_reg[10];
  assign Delay1_reg_next[12] = Delay1_reg[11];
  assign Delay1_reg_next[13] = Delay1_reg[12];
  assign Delay1_reg_next[14] = Delay1_reg[13];
  assign Delay1_reg_next[15] = Delay1_reg[14];
  assign Delay1_reg_next[16] = Delay1_reg[15];
  assign Delay1_reg_next[17] = Delay1_reg[16];
  assign Delay1_reg_next[18] = Delay1_reg[17];
  assign Delay1_reg_next[19] = Delay1_reg[18];
  assign Delay1_reg_next[20] = Delay1_reg[19];
  assign Delay1_reg_next[21] = Delay1_reg[20];
  assign Delay1_reg_next[22] = Delay1_reg[21];
  assign Delay1_reg_next[23] = Delay1_reg[22];
  assign Delay1_reg_next[24] = Delay1_reg[23];
  assign Delay1_reg_next[25] = Delay1_reg[24];
  assign Delay1_reg_next[26] = Delay1_reg[25];
  assign Delay1_reg_next[27] = Delay1_reg[26];
  assign Delay1_reg_next[28] = Delay1_reg[27];
  assign Delay1_reg_next[29] = Delay1_reg[28];
  assign Delay1_reg_next[30] = Delay1_reg[29];
  assign Delay1_reg_next[31] = Delay1_reg[30];
  assign Delay1_reg_next[32] = Delay1_reg[31];
  assign Delay1_reg_next[33] = Delay1_reg[32];
  assign Delay1_reg_next[34] = Delay1_reg[33];
  assign Delay1_reg_next[35] = Delay1_reg[34];
  assign Delay1_reg_next[36] = Delay1_reg[35];
  assign Delay1_reg_next[37] = Delay1_reg[36];
  assign Delay1_reg_next[38] = Delay1_reg[37];
  assign Delay1_reg_next[39] = Delay1_reg[38];
  assign Delay1_reg_next[40] = Delay1_reg[39];
  assign Delay1_reg_next[41] = Delay1_reg[40];
  assign Delay1_reg_next[42] = Delay1_reg[41];
  assign Delay1_reg_next[43] = Delay1_reg[42];
  assign Delay1_reg_next[44] = Delay1_reg[43];
  assign Delay1_reg_next[45] = Delay1_reg[44];
  assign Delay1_reg_next[46] = Delay1_reg[45];
  assign Delay1_reg_next[47] = Delay1_reg[46];
  assign Delay1_reg_next[48] = Delay1_reg[47];
  assign Delay1_reg_next[49] = Delay1_reg[48];
  assign Delay1_reg_next[50] = Delay1_reg[49];
  assign Delay1_reg_next[51] = Delay1_reg[50];
  assign Delay1_reg_next[52] = Delay1_reg[51];
  assign Delay1_reg_next[53] = Delay1_reg[52];
  assign Delay1_reg_next[54] = Delay1_reg[53];
  assign Delay1_reg_next[55] = Delay1_reg[54];
  assign Delay1_reg_next[56] = Delay1_reg[55];
  assign Delay1_reg_next[57] = Delay1_reg[56];
  assign Delay1_reg_next[58] = Delay1_reg[57];
  assign Delay1_reg_next[59] = Delay1_reg[58];
  assign Delay1_reg_next[60] = Delay1_reg[59];
  assign Delay1_reg_next[61] = Delay1_reg[60];
  assign Delay1_reg_next[62] = Delay1_reg[61];
  assign Delay1_reg_next[63] = Delay1_reg[62];
  assign Delay1_reg_next[64] = Delay1_reg[63];
  assign Delay1_reg_next[65] = Delay1_reg[64];
  assign Delay1_reg_next[66] = Delay1_reg[65];
  assign Delay1_reg_next[67] = Delay1_reg[66];
  assign Delay1_reg_next[68] = Delay1_reg[67];
  assign Delay1_reg_next[69] = Delay1_reg[68];
  assign Delay1_reg_next[70] = Delay1_reg[69];
  assign Delay1_reg_next[71] = Delay1_reg[70];
  assign Delay1_reg_next[72] = Delay1_reg[71];
  assign Delay1_reg_next[73] = Delay1_reg[72];
  assign Delay1_reg_next[74] = Delay1_reg[73];
  assign Delay1_reg_next[75] = Delay1_reg[74];
  assign Delay1_reg_next[76] = Delay1_reg[75];
  assign Delay1_reg_next[77] = Delay1_reg[76];
  assign Delay1_reg_next[78] = Delay1_reg[77];
  assign Delay1_reg_next[79] = Delay1_reg[78];
  assign Delay1_reg_next[80] = Delay1_reg[79];
  assign Delay1_reg_next[81] = Delay1_reg[80];
  assign Delay1_reg_next[82] = Delay1_reg[81];
  assign Delay1_reg_next[83] = Delay1_reg[82];
  assign Delay1_reg_next[84] = Delay1_reg[83];
  assign Delay1_reg_next[85] = Delay1_reg[84];
  assign Delay1_reg_next[86] = Delay1_reg[85];
  assign Delay1_reg_next[87] = Delay1_reg[86];
  assign Delay1_reg_next[88] = Delay1_reg[87];
  assign Delay1_reg_next[89] = Delay1_reg[88];
  assign Delay1_reg_next[90] = Delay1_reg[89];
  assign Delay1_reg_next[91] = Delay1_reg[90];
  assign Delay1_reg_next[92] = Delay1_reg[91];
  assign Delay1_reg_next[93] = Delay1_reg[92];
  assign Delay1_reg_next[94] = Delay1_reg[93];
  assign Delay1_reg_next[95] = Delay1_reg[94];
  assign Delay1_reg_next[96] = Delay1_reg[95];
  assign Delay1_reg_next[97] = Delay1_reg[96];
  assign Delay1_reg_next[98] = Delay1_reg[97];
  assign Delay1_reg_next[99] = Delay1_reg[98];
  assign Delay1_reg_next[100] = Delay1_reg[99];



  always @(posedge clk or posedge reset)
    begin : Subtract_Previous_process
      if (reset == 1'b1) begin
        Subtract_Previous_reg[0] <= 34'sh000000000;
        Subtract_Previous_reg[1] <= 34'sh000000000;
        Subtract_Previous_reg[2] <= 34'sh000000000;
        Subtract_Previous_reg[3] <= 34'sh000000000;
        Subtract_Previous_reg[4] <= 34'sh000000000;
        Subtract_Previous_reg[5] <= 34'sh000000000;
        Subtract_Previous_reg[6] <= 34'sh000000000;
        Subtract_Previous_reg[7] <= 34'sh000000000;
        Subtract_Previous_reg[8] <= 34'sh000000000;
        Subtract_Previous_reg[9] <= 34'sh000000000;
        Subtract_Previous_reg[10] <= 34'sh000000000;
        Subtract_Previous_reg[11] <= 34'sh000000000;
        Subtract_Previous_reg[12] <= 34'sh000000000;
        Subtract_Previous_reg[13] <= 34'sh000000000;
        Subtract_Previous_reg[14] <= 34'sh000000000;
        Subtract_Previous_reg[15] <= 34'sh000000000;
        Subtract_Previous_reg[16] <= 34'sh000000000;
        Subtract_Previous_reg[17] <= 34'sh000000000;
        Subtract_Previous_reg[18] <= 34'sh000000000;
        Subtract_Previous_reg[19] <= 34'sh000000000;
        Subtract_Previous_reg[20] <= 34'sh000000000;
        Subtract_Previous_reg[21] <= 34'sh000000000;
        Subtract_Previous_reg[22] <= 34'sh000000000;
        Subtract_Previous_reg[23] <= 34'sh000000000;
        Subtract_Previous_reg[24] <= 34'sh000000000;
        Subtract_Previous_reg[25] <= 34'sh000000000;
        Subtract_Previous_reg[26] <= 34'sh000000000;
        Subtract_Previous_reg[27] <= 34'sh000000000;
        Subtract_Previous_reg[28] <= 34'sh000000000;
        Subtract_Previous_reg[29] <= 34'sh000000000;
        Subtract_Previous_reg[30] <= 34'sh000000000;
        Subtract_Previous_reg[31] <= 34'sh000000000;
        Subtract_Previous_reg[32] <= 34'sh000000000;
        Subtract_Previous_reg[33] <= 34'sh000000000;
        Subtract_Previous_reg[34] <= 34'sh000000000;
        Subtract_Previous_reg[35] <= 34'sh000000000;
        Subtract_Previous_reg[36] <= 34'sh000000000;
        Subtract_Previous_reg[37] <= 34'sh000000000;
        Subtract_Previous_reg[38] <= 34'sh000000000;
        Subtract_Previous_reg[39] <= 34'sh000000000;
        Subtract_Previous_reg[40] <= 34'sh000000000;
        Subtract_Previous_reg[41] <= 34'sh000000000;
        Subtract_Previous_reg[42] <= 34'sh000000000;
        Subtract_Previous_reg[43] <= 34'sh000000000;
        Subtract_Previous_reg[44] <= 34'sh000000000;
        Subtract_Previous_reg[45] <= 34'sh000000000;
        Subtract_Previous_reg[46] <= 34'sh000000000;
        Subtract_Previous_reg[47] <= 34'sh000000000;
        Subtract_Previous_reg[48] <= 34'sh000000000;
        Subtract_Previous_reg[49] <= 34'sh000000000;
        Subtract_Previous_reg[50] <= 34'sh000000000;
        Subtract_Previous_reg[51] <= 34'sh000000000;
        Subtract_Previous_reg[52] <= 34'sh000000000;
        Subtract_Previous_reg[53] <= 34'sh000000000;
        Subtract_Previous_reg[54] <= 34'sh000000000;
        Subtract_Previous_reg[55] <= 34'sh000000000;
        Subtract_Previous_reg[56] <= 34'sh000000000;
        Subtract_Previous_reg[57] <= 34'sh000000000;
        Subtract_Previous_reg[58] <= 34'sh000000000;
        Subtract_Previous_reg[59] <= 34'sh000000000;
        Subtract_Previous_reg[60] <= 34'sh000000000;
        Subtract_Previous_reg[61] <= 34'sh000000000;
        Subtract_Previous_reg[62] <= 34'sh000000000;
        Subtract_Previous_reg[63] <= 34'sh000000000;
        Subtract_Previous_reg[64] <= 34'sh000000000;
        Subtract_Previous_reg[65] <= 34'sh000000000;
        Subtract_Previous_reg[66] <= 34'sh000000000;
        Subtract_Previous_reg[67] <= 34'sh000000000;
        Subtract_Previous_reg[68] <= 34'sh000000000;
        Subtract_Previous_reg[69] <= 34'sh000000000;
        Subtract_Previous_reg[70] <= 34'sh000000000;
        Subtract_Previous_reg[71] <= 34'sh000000000;
        Subtract_Previous_reg[72] <= 34'sh000000000;
        Subtract_Previous_reg[73] <= 34'sh000000000;
        Subtract_Previous_reg[74] <= 34'sh000000000;
        Subtract_Previous_reg[75] <= 34'sh000000000;
        Subtract_Previous_reg[76] <= 34'sh000000000;
        Subtract_Previous_reg[77] <= 34'sh000000000;
        Subtract_Previous_reg[78] <= 34'sh000000000;
        Subtract_Previous_reg[79] <= 34'sh000000000;
        Subtract_Previous_reg[80] <= 34'sh000000000;
        Subtract_Previous_reg[81] <= 34'sh000000000;
        Subtract_Previous_reg[82] <= 34'sh000000000;
        Subtract_Previous_reg[83] <= 34'sh000000000;
        Subtract_Previous_reg[84] <= 34'sh000000000;
        Subtract_Previous_reg[85] <= 34'sh000000000;
        Subtract_Previous_reg[86] <= 34'sh000000000;
        Subtract_Previous_reg[87] <= 34'sh000000000;
        Subtract_Previous_reg[88] <= 34'sh000000000;
        Subtract_Previous_reg[89] <= 34'sh000000000;
        Subtract_Previous_reg[90] <= 34'sh000000000;
        Subtract_Previous_reg[91] <= 34'sh000000000;
        Subtract_Previous_reg[92] <= 34'sh000000000;
        Subtract_Previous_reg[93] <= 34'sh000000000;
        Subtract_Previous_reg[94] <= 34'sh000000000;
        Subtract_Previous_reg[95] <= 34'sh000000000;
        Subtract_Previous_reg[96] <= 34'sh000000000;
        Subtract_Previous_reg[97] <= 34'sh000000000;
        Subtract_Previous_reg[98] <= 34'sh000000000;
        Subtract_Previous_reg[99] <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Subtract_Previous_reg[0] <= Subtract_Previous_reg_next[0];
          Subtract_Previous_reg[1] <= Subtract_Previous_reg_next[1];
          Subtract_Previous_reg[2] <= Subtract_Previous_reg_next[2];
          Subtract_Previous_reg[3] <= Subtract_Previous_reg_next[3];
          Subtract_Previous_reg[4] <= Subtract_Previous_reg_next[4];
          Subtract_Previous_reg[5] <= Subtract_Previous_reg_next[5];
          Subtract_Previous_reg[6] <= Subtract_Previous_reg_next[6];
          Subtract_Previous_reg[7] <= Subtract_Previous_reg_next[7];
          Subtract_Previous_reg[8] <= Subtract_Previous_reg_next[8];
          Subtract_Previous_reg[9] <= Subtract_Previous_reg_next[9];
          Subtract_Previous_reg[10] <= Subtract_Previous_reg_next[10];
          Subtract_Previous_reg[11] <= Subtract_Previous_reg_next[11];
          Subtract_Previous_reg[12] <= Subtract_Previous_reg_next[12];
          Subtract_Previous_reg[13] <= Subtract_Previous_reg_next[13];
          Subtract_Previous_reg[14] <= Subtract_Previous_reg_next[14];
          Subtract_Previous_reg[15] <= Subtract_Previous_reg_next[15];
          Subtract_Previous_reg[16] <= Subtract_Previous_reg_next[16];
          Subtract_Previous_reg[17] <= Subtract_Previous_reg_next[17];
          Subtract_Previous_reg[18] <= Subtract_Previous_reg_next[18];
          Subtract_Previous_reg[19] <= Subtract_Previous_reg_next[19];
          Subtract_Previous_reg[20] <= Subtract_Previous_reg_next[20];
          Subtract_Previous_reg[21] <= Subtract_Previous_reg_next[21];
          Subtract_Previous_reg[22] <= Subtract_Previous_reg_next[22];
          Subtract_Previous_reg[23] <= Subtract_Previous_reg_next[23];
          Subtract_Previous_reg[24] <= Subtract_Previous_reg_next[24];
          Subtract_Previous_reg[25] <= Subtract_Previous_reg_next[25];
          Subtract_Previous_reg[26] <= Subtract_Previous_reg_next[26];
          Subtract_Previous_reg[27] <= Subtract_Previous_reg_next[27];
          Subtract_Previous_reg[28] <= Subtract_Previous_reg_next[28];
          Subtract_Previous_reg[29] <= Subtract_Previous_reg_next[29];
          Subtract_Previous_reg[30] <= Subtract_Previous_reg_next[30];
          Subtract_Previous_reg[31] <= Subtract_Previous_reg_next[31];
          Subtract_Previous_reg[32] <= Subtract_Previous_reg_next[32];
          Subtract_Previous_reg[33] <= Subtract_Previous_reg_next[33];
          Subtract_Previous_reg[34] <= Subtract_Previous_reg_next[34];
          Subtract_Previous_reg[35] <= Subtract_Previous_reg_next[35];
          Subtract_Previous_reg[36] <= Subtract_Previous_reg_next[36];
          Subtract_Previous_reg[37] <= Subtract_Previous_reg_next[37];
          Subtract_Previous_reg[38] <= Subtract_Previous_reg_next[38];
          Subtract_Previous_reg[39] <= Subtract_Previous_reg_next[39];
          Subtract_Previous_reg[40] <= Subtract_Previous_reg_next[40];
          Subtract_Previous_reg[41] <= Subtract_Previous_reg_next[41];
          Subtract_Previous_reg[42] <= Subtract_Previous_reg_next[42];
          Subtract_Previous_reg[43] <= Subtract_Previous_reg_next[43];
          Subtract_Previous_reg[44] <= Subtract_Previous_reg_next[44];
          Subtract_Previous_reg[45] <= Subtract_Previous_reg_next[45];
          Subtract_Previous_reg[46] <= Subtract_Previous_reg_next[46];
          Subtract_Previous_reg[47] <= Subtract_Previous_reg_next[47];
          Subtract_Previous_reg[48] <= Subtract_Previous_reg_next[48];
          Subtract_Previous_reg[49] <= Subtract_Previous_reg_next[49];
          Subtract_Previous_reg[50] <= Subtract_Previous_reg_next[50];
          Subtract_Previous_reg[51] <= Subtract_Previous_reg_next[51];
          Subtract_Previous_reg[52] <= Subtract_Previous_reg_next[52];
          Subtract_Previous_reg[53] <= Subtract_Previous_reg_next[53];
          Subtract_Previous_reg[54] <= Subtract_Previous_reg_next[54];
          Subtract_Previous_reg[55] <= Subtract_Previous_reg_next[55];
          Subtract_Previous_reg[56] <= Subtract_Previous_reg_next[56];
          Subtract_Previous_reg[57] <= Subtract_Previous_reg_next[57];
          Subtract_Previous_reg[58] <= Subtract_Previous_reg_next[58];
          Subtract_Previous_reg[59] <= Subtract_Previous_reg_next[59];
          Subtract_Previous_reg[60] <= Subtract_Previous_reg_next[60];
          Subtract_Previous_reg[61] <= Subtract_Previous_reg_next[61];
          Subtract_Previous_reg[62] <= Subtract_Previous_reg_next[62];
          Subtract_Previous_reg[63] <= Subtract_Previous_reg_next[63];
          Subtract_Previous_reg[64] <= Subtract_Previous_reg_next[64];
          Subtract_Previous_reg[65] <= Subtract_Previous_reg_next[65];
          Subtract_Previous_reg[66] <= Subtract_Previous_reg_next[66];
          Subtract_Previous_reg[67] <= Subtract_Previous_reg_next[67];
          Subtract_Previous_reg[68] <= Subtract_Previous_reg_next[68];
          Subtract_Previous_reg[69] <= Subtract_Previous_reg_next[69];
          Subtract_Previous_reg[70] <= Subtract_Previous_reg_next[70];
          Subtract_Previous_reg[71] <= Subtract_Previous_reg_next[71];
          Subtract_Previous_reg[72] <= Subtract_Previous_reg_next[72];
          Subtract_Previous_reg[73] <= Subtract_Previous_reg_next[73];
          Subtract_Previous_reg[74] <= Subtract_Previous_reg_next[74];
          Subtract_Previous_reg[75] <= Subtract_Previous_reg_next[75];
          Subtract_Previous_reg[76] <= Subtract_Previous_reg_next[76];
          Subtract_Previous_reg[77] <= Subtract_Previous_reg_next[77];
          Subtract_Previous_reg[78] <= Subtract_Previous_reg_next[78];
          Subtract_Previous_reg[79] <= Subtract_Previous_reg_next[79];
          Subtract_Previous_reg[80] <= Subtract_Previous_reg_next[80];
          Subtract_Previous_reg[81] <= Subtract_Previous_reg_next[81];
          Subtract_Previous_reg[82] <= Subtract_Previous_reg_next[82];
          Subtract_Previous_reg[83] <= Subtract_Previous_reg_next[83];
          Subtract_Previous_reg[84] <= Subtract_Previous_reg_next[84];
          Subtract_Previous_reg[85] <= Subtract_Previous_reg_next[85];
          Subtract_Previous_reg[86] <= Subtract_Previous_reg_next[86];
          Subtract_Previous_reg[87] <= Subtract_Previous_reg_next[87];
          Subtract_Previous_reg[88] <= Subtract_Previous_reg_next[88];
          Subtract_Previous_reg[89] <= Subtract_Previous_reg_next[89];
          Subtract_Previous_reg[90] <= Subtract_Previous_reg_next[90];
          Subtract_Previous_reg[91] <= Subtract_Previous_reg_next[91];
          Subtract_Previous_reg[92] <= Subtract_Previous_reg_next[92];
          Subtract_Previous_reg[93] <= Subtract_Previous_reg_next[93];
          Subtract_Previous_reg[94] <= Subtract_Previous_reg_next[94];
          Subtract_Previous_reg[95] <= Subtract_Previous_reg_next[95];
          Subtract_Previous_reg[96] <= Subtract_Previous_reg_next[96];
          Subtract_Previous_reg[97] <= Subtract_Previous_reg_next[97];
          Subtract_Previous_reg[98] <= Subtract_Previous_reg_next[98];
          Subtract_Previous_reg[99] <= Subtract_Previous_reg_next[99];
        end
      end
    end

  assign Subtract_Previous_out1 = Subtract_Previous_reg[99];
  assign Subtract_Previous_reg_next[0] = Delay1_out1;
  assign Subtract_Previous_reg_next[1] = Subtract_Previous_reg[0];
  assign Subtract_Previous_reg_next[2] = Subtract_Previous_reg[1];
  assign Subtract_Previous_reg_next[3] = Subtract_Previous_reg[2];
  assign Subtract_Previous_reg_next[4] = Subtract_Previous_reg[3];
  assign Subtract_Previous_reg_next[5] = Subtract_Previous_reg[4];
  assign Subtract_Previous_reg_next[6] = Subtract_Previous_reg[5];
  assign Subtract_Previous_reg_next[7] = Subtract_Previous_reg[6];
  assign Subtract_Previous_reg_next[8] = Subtract_Previous_reg[7];
  assign Subtract_Previous_reg_next[9] = Subtract_Previous_reg[8];
  assign Subtract_Previous_reg_next[10] = Subtract_Previous_reg[9];
  assign Subtract_Previous_reg_next[11] = Subtract_Previous_reg[10];
  assign Subtract_Previous_reg_next[12] = Subtract_Previous_reg[11];
  assign Subtract_Previous_reg_next[13] = Subtract_Previous_reg[12];
  assign Subtract_Previous_reg_next[14] = Subtract_Previous_reg[13];
  assign Subtract_Previous_reg_next[15] = Subtract_Previous_reg[14];
  assign Subtract_Previous_reg_next[16] = Subtract_Previous_reg[15];
  assign Subtract_Previous_reg_next[17] = Subtract_Previous_reg[16];
  assign Subtract_Previous_reg_next[18] = Subtract_Previous_reg[17];
  assign Subtract_Previous_reg_next[19] = Subtract_Previous_reg[18];
  assign Subtract_Previous_reg_next[20] = Subtract_Previous_reg[19];
  assign Subtract_Previous_reg_next[21] = Subtract_Previous_reg[20];
  assign Subtract_Previous_reg_next[22] = Subtract_Previous_reg[21];
  assign Subtract_Previous_reg_next[23] = Subtract_Previous_reg[22];
  assign Subtract_Previous_reg_next[24] = Subtract_Previous_reg[23];
  assign Subtract_Previous_reg_next[25] = Subtract_Previous_reg[24];
  assign Subtract_Previous_reg_next[26] = Subtract_Previous_reg[25];
  assign Subtract_Previous_reg_next[27] = Subtract_Previous_reg[26];
  assign Subtract_Previous_reg_next[28] = Subtract_Previous_reg[27];
  assign Subtract_Previous_reg_next[29] = Subtract_Previous_reg[28];
  assign Subtract_Previous_reg_next[30] = Subtract_Previous_reg[29];
  assign Subtract_Previous_reg_next[31] = Subtract_Previous_reg[30];
  assign Subtract_Previous_reg_next[32] = Subtract_Previous_reg[31];
  assign Subtract_Previous_reg_next[33] = Subtract_Previous_reg[32];
  assign Subtract_Previous_reg_next[34] = Subtract_Previous_reg[33];
  assign Subtract_Previous_reg_next[35] = Subtract_Previous_reg[34];
  assign Subtract_Previous_reg_next[36] = Subtract_Previous_reg[35];
  assign Subtract_Previous_reg_next[37] = Subtract_Previous_reg[36];
  assign Subtract_Previous_reg_next[38] = Subtract_Previous_reg[37];
  assign Subtract_Previous_reg_next[39] = Subtract_Previous_reg[38];
  assign Subtract_Previous_reg_next[40] = Subtract_Previous_reg[39];
  assign Subtract_Previous_reg_next[41] = Subtract_Previous_reg[40];
  assign Subtract_Previous_reg_next[42] = Subtract_Previous_reg[41];
  assign Subtract_Previous_reg_next[43] = Subtract_Previous_reg[42];
  assign Subtract_Previous_reg_next[44] = Subtract_Previous_reg[43];
  assign Subtract_Previous_reg_next[45] = Subtract_Previous_reg[44];
  assign Subtract_Previous_reg_next[46] = Subtract_Previous_reg[45];
  assign Subtract_Previous_reg_next[47] = Subtract_Previous_reg[46];
  assign Subtract_Previous_reg_next[48] = Subtract_Previous_reg[47];
  assign Subtract_Previous_reg_next[49] = Subtract_Previous_reg[48];
  assign Subtract_Previous_reg_next[50] = Subtract_Previous_reg[49];
  assign Subtract_Previous_reg_next[51] = Subtract_Previous_reg[50];
  assign Subtract_Previous_reg_next[52] = Subtract_Previous_reg[51];
  assign Subtract_Previous_reg_next[53] = Subtract_Previous_reg[52];
  assign Subtract_Previous_reg_next[54] = Subtract_Previous_reg[53];
  assign Subtract_Previous_reg_next[55] = Subtract_Previous_reg[54];
  assign Subtract_Previous_reg_next[56] = Subtract_Previous_reg[55];
  assign Subtract_Previous_reg_next[57] = Subtract_Previous_reg[56];
  assign Subtract_Previous_reg_next[58] = Subtract_Previous_reg[57];
  assign Subtract_Previous_reg_next[59] = Subtract_Previous_reg[58];
  assign Subtract_Previous_reg_next[60] = Subtract_Previous_reg[59];
  assign Subtract_Previous_reg_next[61] = Subtract_Previous_reg[60];
  assign Subtract_Previous_reg_next[62] = Subtract_Previous_reg[61];
  assign Subtract_Previous_reg_next[63] = Subtract_Previous_reg[62];
  assign Subtract_Previous_reg_next[64] = Subtract_Previous_reg[63];
  assign Subtract_Previous_reg_next[65] = Subtract_Previous_reg[64];
  assign Subtract_Previous_reg_next[66] = Subtract_Previous_reg[65];
  assign Subtract_Previous_reg_next[67] = Subtract_Previous_reg[66];
  assign Subtract_Previous_reg_next[68] = Subtract_Previous_reg[67];
  assign Subtract_Previous_reg_next[69] = Subtract_Previous_reg[68];
  assign Subtract_Previous_reg_next[70] = Subtract_Previous_reg[69];
  assign Subtract_Previous_reg_next[71] = Subtract_Previous_reg[70];
  assign Subtract_Previous_reg_next[72] = Subtract_Previous_reg[71];
  assign Subtract_Previous_reg_next[73] = Subtract_Previous_reg[72];
  assign Subtract_Previous_reg_next[74] = Subtract_Previous_reg[73];
  assign Subtract_Previous_reg_next[75] = Subtract_Previous_reg[74];
  assign Subtract_Previous_reg_next[76] = Subtract_Previous_reg[75];
  assign Subtract_Previous_reg_next[77] = Subtract_Previous_reg[76];
  assign Subtract_Previous_reg_next[78] = Subtract_Previous_reg[77];
  assign Subtract_Previous_reg_next[79] = Subtract_Previous_reg[78];
  assign Subtract_Previous_reg_next[80] = Subtract_Previous_reg[79];
  assign Subtract_Previous_reg_next[81] = Subtract_Previous_reg[80];
  assign Subtract_Previous_reg_next[82] = Subtract_Previous_reg[81];
  assign Subtract_Previous_reg_next[83] = Subtract_Previous_reg[82];
  assign Subtract_Previous_reg_next[84] = Subtract_Previous_reg[83];
  assign Subtract_Previous_reg_next[85] = Subtract_Previous_reg[84];
  assign Subtract_Previous_reg_next[86] = Subtract_Previous_reg[85];
  assign Subtract_Previous_reg_next[87] = Subtract_Previous_reg[86];
  assign Subtract_Previous_reg_next[88] = Subtract_Previous_reg[87];
  assign Subtract_Previous_reg_next[89] = Subtract_Previous_reg[88];
  assign Subtract_Previous_reg_next[90] = Subtract_Previous_reg[89];
  assign Subtract_Previous_reg_next[91] = Subtract_Previous_reg[90];
  assign Subtract_Previous_reg_next[92] = Subtract_Previous_reg[91];
  assign Subtract_Previous_reg_next[93] = Subtract_Previous_reg[92];
  assign Subtract_Previous_reg_next[94] = Subtract_Previous_reg[93];
  assign Subtract_Previous_reg_next[95] = Subtract_Previous_reg[94];
  assign Subtract_Previous_reg_next[96] = Subtract_Previous_reg[95];
  assign Subtract_Previous_reg_next[97] = Subtract_Previous_reg[96];
  assign Subtract_Previous_reg_next[98] = Subtract_Previous_reg[97];
  assign Subtract_Previous_reg_next[99] = Subtract_Previous_reg[98];



  assign Add2_out1 = Delay1_out1 - Subtract_Previous_out1;



  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= Add2_out1;
        end
      end
    end



  assign Add3_add_cast = {Delay3_out1[33], Delay3_out1};
  assign Add3_add_cast_1 = {Delay7_out1[33], Delay7_out1};
  assign Add3_add_temp = Add3_add_cast + Add3_add_cast_1;
  assign Add3_out1 = ((Add3_add_temp[34] == 1'b0) && (Add3_add_temp[33] != 1'b0) ? 34'sh1FFFFFFFF :
              ((Add3_add_temp[34] == 1'b1) && (Add3_add_temp[33] != 1'b1) ? 34'sh200000000 :
              $signed(Add3_add_temp[33:0])));



  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay7_out1 <= Add3_out1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_reg[0] <= 34'sh000000000;
        Delay2_reg[1] <= 34'sh000000000;
        Delay2_reg[2] <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Delay2_reg[0] <= Delay2_reg_next[0];
          Delay2_reg[1] <= Delay2_reg_next[1];
          Delay2_reg[2] <= Delay2_reg_next[2];
        end
      end
    end

  assign Delay2_out1 = Delay2_reg[2];
  assign Delay2_reg_next[0] = Delay7_out1;
  assign Delay2_reg_next[1] = Delay2_reg[0];
  assign Delay2_reg_next[2] = Delay2_reg[1];



  assign Lead_Sum = Delay2_out1;

endmodule  // Lead_Cells_HDL

