// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\SimulinkCFARHDLWorkflowExampleNew\Validate.v
// Created: 2023-05-30 17:04:47
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Validate
// Source Path: SimulinkCFARHDLWorkflowExampleNew/CFAR Implementation Model/Validate
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Validate
          (Threshold,
           Detection,
           Valid,
           vDetection,
           vThreshold,
           ValidOut);


  input   signed [33:0] Threshold;  // sfix34_En12
  input   Detection;
  input   Valid;
  output  vDetection;
  output  signed [11:0] vThreshold;  // sfix12_En8
  output  ValidOut;


  wire Constant1_out1;
  wire Switch2_out1;
  wire signed [33:0] Constant2_out1;  // sfix34_En12
  wire signed [11:0] Constant2_out1_dtc;  // sfix12_En8
  wire signed [11:0] Threshold_dtc;  // sfix12_En8
  wire signed [11:0] Switch1_out1;  // sfix12_En8


  assign Constant1_out1 = 1'b0;



  assign Switch2_out1 = (Valid == 1'b0 ? Constant1_out1 :
              Detection);



  assign vDetection = Switch2_out1;

  assign Constant2_out1 = 34'sh000000000;



  assign Constant2_out1_dtc = Constant2_out1[15:4];



  assign Threshold_dtc = Threshold[15:4];



  assign Switch1_out1 = (Valid == 1'b0 ? Constant2_out1_dtc :
              Threshold_dtc);



  assign vThreshold = Switch1_out1;

  assign ValidOut = Valid;

endmodule  // Validate

